-- Equipment type → reading type mappings
CREATE TABLE IF NOT EXISTS equipment_reading_mappings (
  id                   SERIAL PRIMARY KEY,
  equipment_type_name  VARCHAR(100) NOT NULL,
  reading_type_id      INTEGER      NOT NULL REFERENCES reading_types(id) ON DELETE CASCADE,
  mandatory            BOOLEAN      NOT NULL DEFAULT true,
  display_order        INTEGER      NOT NULL DEFAULT 1,
  created_at           TIMESTAMPTZ  DEFAULT NOW(),
  UNIQUE(equipment_type_name, reading_type_id)
);

-- Seed from Excel: Equipment_Reading_Mapping sheet
-- Uses sub-select to resolve reading_type_id by code (safe even if order changes)
INSERT INTO equipment_reading_mappings (equipment_type_name, reading_type_id, mandatory, display_order)
SELECT t.name, rt.id, t.mandatory, t.ord FROM (VALUES
  ('Ambulance',                       'KMS',       true, 1),
  ('Backhoe loader',                  'ENG_HRS',   true, 1),
  ('Bitumen Sprayer',                 'KMS',       true, 1),
  ('Bitumen Sprayer',                 'ENG_HRS',   true, 2),
  ('Chain Dozer',                     'ENG_HRS',   true, 1),
  ('Concrete Batching Plant',         'MIXER_HRS', true, 1),
  ('Concrete Boom Placer',            'ENG_HRS',   true, 1),
  ('Concrete Boom Placer',            'PUMP_HRS',  true, 2),
  ('Concrete Pump',                   'ENG_HRS',   true, 1),
  ('Concrete Pump',                   'PUMP_HRS',  true, 2),
  ('Crawler Crane',                   'ENG_HRS',   true, 1),
  ('De-Watering pumps',               'ENG_HRS',   true, 1),
  ('Diesel Generator',                'ENG_HRS',   true, 1),
  ('Twin Boom Drill Jumbo',           'ENG_HRS',   true, 1),
  ('Twin Boom Drill Jumbo',           'COMP_HRS',  true, 2),
  ('Twin Boom Drill Jumbo',           'BOOM1_HRS', true, 3),
  ('Twin Boom Drill Jumbo',           'BOOM2_HRS', true, 4),
  ('Three Boom Drill Jumbo',          'ENG_HRS',   true, 1),
  ('Three Boom Drill Jumbo',          'COMP_HRS',  true, 2),
  ('Three Boom Drill Jumbo',          'BOOM1_HRS', true, 3),
  ('Three Boom Drill Jumbo',          'BOOM2_HRS', true, 4),
  ('Three Boom Drill Jumbo',          'BOOM3_HRS', true, 5),
  ('Excavator',                       'ENG_HRS',   true, 1),
  ('Excavator With Tele Dipper',      'ENG_HRS',   true, 1),
  ('Kerb Paver',                      'ENG_HRS',   true, 1),
  ('Mobile Diesel Browser',           'KMS',       true, 1),
  ('Mobile Diesel Browser',           'ENG_HRS',   true, 2),
  ('Towable Tower Light',             'ENG_HRS',   true, 1),
  ('Mobile Service Van',              'KMS',       true, 1),
  ('Mobile Service Van',              'ENG_HRS',   true, 2),
  ('Mobile Water Tanker',             'KMS',       true, 1),
  ('Modular JackUp Barge',            'ENG_HRS',   true, 1),
  ('Motorcycle',                      'KMS',       true, 1),
  ('Motor Grader',                    'ENG_HRS',   true, 1),
  ('Passenger bus',                   'KMS',       true, 1),
  ('Pick and Carry Crane',            'ENG_HRS',   true, 1),
  ('Piling Rig',                      'ENG_HRS',   true, 1),
  ('Pneumatic Tyre Roller',           'ENG_HRS',   true, 1),
  ('Road Sweeper-Truck mounted',      'ENG_HRS',   true, 1),
  ('Sand Washing Plant',              'ENG_HRS',   true, 1),
  ('Screw Air Compressor-Diesel',     'ENG_HRS',   true, 1),
  ('Screw Air Compressor-Electric',   'MOTOR_HRS', true, 1),
  ('Self loading concrete mixer',     'ENG_HRS',   true, 1),
  ('Shotcrete Machine',               'ENG_HRS',   true, 1),
  ('Shotcrete Machine',               'COMP_HRS',  true, 2),
  ('Shotcrete Machine',               'MOTOR_HRS', true, 3),
  ('Slip-form Paver',                 'ENG_HRS',   true, 1),
  ('Tandem Vibratory Compactor',      'ENG_HRS',   true, 1),
  ('Telehandler',                     'ENG_HRS',   true, 1),
  ('Texture Curing Machine',          'ENG_HRS',   true, 1),
  ('Tipper',                          'KMS',       true, 1),
  ('Tipper',                          'ENG_HRS',   true, 2),
  ('Track pavers',                    'ENG_HRS',   true, 1),
  ('Tractor Dozer',                   'ENG_HRS',   true, 1),
  ('Tractor Tanker',                  'ENG_HRS',   true, 1),
  ('Tractor With Blade',              'ENG_HRS',   true, 1),
  ('Tractor with Trolly',             'ENG_HRS',   true, 1),
  ('Transit Mixer',                   'KMS',       true, 1),
  ('Transit Mixer',                   'DRUM_HRS',  true, 2),
  ('TugBoat',                         'ENG_HRS',   true, 1),
  ('Twin Boom Platform Lifter',       'ENG_HRS',   true, 1),
  ('Tyre Mounted Telescopic Crane',   'ENG_HRS',   true, 1),
  ('Utility Vehicle - LMV',          'KMS',       true, 1),
  ('Vibratory Compactor',             'ENG_HRS',   true, 1),
  ('Walk Behind Vibratory Roller',    'ENG_HRS',   true, 1),
  ('Wheel Loader',                    'ENG_HRS',   true, 1),
  ('Fork Lift',                       'ENG_HRS',   true, 1),
  ('Man Lifter',                      'ENG_HRS',   true, 1),
  ('Boom Lift',                       'ENG_HRS',   true, 1),
  ('Skid Steer Loader',               'ENG_HRS',   true, 1)
) AS t(name, rcode, mandatory, ord)
JOIN reading_types rt ON rt.code = t.rcode
ON CONFLICT (equipment_type_name, reading_type_id) DO NOTHING;
