-- Add asset_group and asset_cat columns to equipment_types
ALTER TABLE equipment_types
  ADD COLUMN IF NOT EXISTS asset_group VARCHAR(100),
  ADD COLUMN IF NOT EXISTS asset_cat   VARCHAR(100);

-- Seed / update all 76 asset names from Plants_Machinery_Asset_Matrix.xlsx
-- asset_group  = Excel "Asset Group"
-- asset_cat    = Excel "Asset Category"
-- asset_category (existing) = Measurable | Non-Measurable
INSERT INTO equipment_types (name, asset_group, asset_cat, asset_category) VALUES
  ('Twin Boom Platform Lifter',          'Aerial Access Equipment',         'Elevated Work Platforms',       'Measurable'),
  ('Scissor Lift',                       'Aerial Access Equipment',         'Elevated Work Platforms',       'Measurable'),
  ('Man Lifter',                         'Aerial Access Equipment',         'Elevated Work Platforms',       'Measurable'),
  ('Boom Lift',                          'Aerial Access Equipment',         'Elevated Work Platforms',       'Measurable'),
  ('De-Watering Pumps - Diesel',         'Air, Power & Pump Equipment',     'Pump Equipment',                'Measurable'),
  ('De-Watering Pumps - Electrical',     'Air, Power & Pump Equipment',     'Pump Equipment',                'Non-Measurable'),
  ('Diesel Generator',                   'Air, Power & Pump Equipment',     'Power Equipment',               'Measurable'),
  ('Screw Air Compressor-Diesel',        'Air, Power & Pump Equipment',     'Compressor Equipment',          'Measurable'),
  ('Screw Air Compressor-Electric',      'Air, Power & Pump Equipment',     'Compressor Equipment',          'Measurable'),
  ('Chiller Plant',                      'Concrete & RMC Equipment',        'Concrete Cooling Equipment',    'Measurable'),
  ('Concrete Batching Plant',            'Concrete & RMC Equipment',        'RMC Equipment',                 'Measurable'),
  ('Concrete Boom Placer',               'Concrete & RMC Equipment',        'Concrete Placement Equipment',  'Measurable'),
  ('Concrete Pump',                      'Concrete & RMC Equipment',        'Concrete Placement Equipment',  'Measurable'),
  ('Self Loading Concrete Mixer',        'Concrete & RMC Equipment',        'RMC Equipment',                 'Measurable'),
  ('Storage Silo',                       'Concrete & RMC Equipment',        'Concrete Storage Equipment',    'Non-Measurable'),
  ('Transit Mixer',                      'Concrete & RMC Equipment',        'RMC Equipment',                 'Measurable'),
  ('Tele Belt',                          'Concrete & RMC Equipment',        'Concrete Placement Equipment',  'Measurable'),
  ('Loop Belt',                          'Concrete & RMC Equipment',        'Concrete Placement Equipment',  'Measurable'),
  ('Crawler Crane',                      'Cranes & Material Handling',      'Heavy Cranes',                  'Measurable'),
  ('Mobile Tower Crane',                 'Cranes & Material Handling',      'Tower Cranes',                  'Measurable'),
  ('Pick and Carry Crane',               'Cranes & Material Handling',      'Mobile Cranes',                 'Measurable'),
  ('Telehandler',                        'Cranes & Material Handling',      'Material Handling Equipment',   'Measurable'),
  ('Tower Crane',                        'Cranes & Material Handling',      'Tower Cranes',                  'Non-Measurable'),
  ('Tyre Mounted Telescopic Crane',      'Cranes & Material Handling',      'Mobile Cranes',                 'Measurable'),
  ('Fork Lift',                          'Cranes & Material Handling',      'Material Handling Equipment',   'Measurable'),
  ('EOT Crane',                          'Cranes & Material Handling',      'Industrial Cranes',             'Non-Measurable'),
  ('Backhoe Loader',                     'Earthmoving Equipment',           'Excavation Equipment',          'Measurable'),
  ('Chain Dozer',                        'Earthmoving Equipment',           'Dozers',                        'Measurable'),
  ('Excavator',                          'Earthmoving Equipment',           'Excavation Equipment',          'Measurable'),
  ('Excavator With Tele Dipper',         'Earthmoving Equipment',           'Excavation Equipment',          'Measurable'),
  ('Tractor Dozer',                      'Earthmoving Equipment',           'Dozers',                        'Measurable'),
  ('Tractor With Blade',                 'Earthmoving Equipment',           'Dozers',                        'Measurable'),
  ('Wheel Loader',                       'Earthmoving Equipment',           'Loading Equipment',             'Measurable'),
  ('Skid Steer Loader',                  'Earthmoving Equipment',           'Loading Equipment',             'Measurable'),
  ('Ambulance',                          'Emergency & Utility Vehicles',    'Emergency Vehicles',            'Measurable'),
  ('Mobile Service Van',                 'Emergency & Utility Vehicles',    'Service Vehicles',              'Measurable'),
  ('Motorcycle',                         'Emergency & Utility Vehicles',    'Utility Vehicles',              'Non-Measurable'),
  ('Camper',                             'Emergency & Utility Vehicles',    'Utility Vehicles',              'Measurable'),
  ('Four Wheelers',                      'Emergency & Utility Vehicles',    'Utility Vehicles',              'Measurable'),
  ('Cruiser',                            'Emergency & Utility Vehicles',    'Utility Vehicles',              'Measurable'),
  ('Pickup',                             'Emergency & Utility Vehicles',    'Utility Vehicles',              'Measurable'),
  ('Piling Rig',                         'Foundation Equipment',            'Piling Equipment',              'Measurable'),
  ('Bar Bending Machine',                'Industrial Equipment',            'Steel Processing Equipment',    'Non-Measurable'),
  ('Bar Cutting Machine',                'Industrial Equipment',            'Steel Processing Equipment',    'Non-Measurable'),
  ('Sand Washing Plant',                 'Industrial Equipment',            'Material Processing Equipment', 'Measurable'),
  ('Weight Bridge',                      'Industrial Equipment',            'Non-Measurable Assets',         'Non-Measurable'),
  ('Modular JackUp Barge',               'Marine Equipment',                'Marine Support Equipment',      'Measurable'),
  ('TugBoat',                            'Marine Equipment',                'Marine Support Equipment',      'Measurable'),
  ('Twin Boom Drill Jumbo',              'Mining & Tunneling Equipment',    'Tunneling Equipment',           'Measurable'),
  ('Three Boom Drill Jumbo',             'Mining & Tunneling Equipment',    'Tunneling Equipment',           'Measurable'),
  ('Pneumatic Crawler Drill Rig (ROC)', 'Mining & Tunneling Equipment',    'Drilling Equipment',            'Non-Measurable'),
  ('Shotcrete Machine',                  'Mining & Tunneling Equipment',    'Underground Support Equipment', 'Measurable'),
  ('Grouting Pump',                      'Mining & Tunneling Equipment',    'Underground Support Equipment', 'Non-Measurable'),
  ('Asphalt Batch Mix Plant',            'Road Construction Equipment',     'Asphalt Equipment',             'Measurable'),
  ('Bitumen Sprayer',                    'Road Construction Equipment',     'Asphalt Equipment',             'Measurable'),
  ('Kerb Cutting Machine',               'Road Construction Equipment',     'Road Finishing Equipment',      'Non-Measurable'),
  ('Kerb Paver',                         'Road Construction Equipment',     'Paving Equipment',              'Measurable'),
  ('Motor Grader',                       'Road Construction Equipment',     'Road Finishing Equipment',      'Measurable'),
  ('Pneumatic Tyre Roller',              'Road Construction Equipment',     'Compaction Equipment',          'Measurable'),
  ('Road Sweeper-Tractor Attachment',    'Road Construction Equipment',     'Road Cleaning Equipment',       'Non-Measurable'),
  ('Road Sweeper-Truck Mounted',         'Road Construction Equipment',     'Road Cleaning Equipment',       'Measurable'),
  ('Slip-form Paver',                    'Road Construction Equipment',     'Paving Equipment',              'Measurable'),
  ('Tandem Vibratory Compactor',         'Road Construction Equipment',     'Compaction Equipment',          'Measurable'),
  ('Texture Curing Machine',             'Road Construction Equipment',     'Road Finishing Equipment',      'Measurable'),
  ('Track Pavers',                       'Road Construction Equipment',     'Paving Equipment',              'Measurable'),
  ('Vibratory Compactor',                'Road Construction Equipment',     'Compaction Equipment',          'Measurable'),
  ('Walk Behind Vibratory Roller',       'Road Construction Equipment',     'Compaction Equipment',          'Measurable'),
  ('Wet Mix Macadam Plant',              'Road Construction Equipment',     'Asphalt Equipment',             'Measurable'),
  ('Tractor Tanker',                     'Tractor & Support Equipment',     'Tanker Equipment',              'Measurable'),
  ('Tractor with Trolly',                'Tractor & Support Equipment',     'Trailer Equipment',             'Measurable'),
  ('Passenger Bus',                      'Transport & Logistics Vehicles',  'Passenger Transport',           'Measurable'),
  ('Tipper',                             'Transport & Logistics Vehicles',  'Material Transport Vehicles',   'Measurable'),
  ('Mobile Diesel Browser',              'Water, Fuel & Lighting Equipment','Fuel Equipment',                'Measurable'),
  ('Towable Tower Light - Diesel',       'Water, Fuel & Lighting Equipment','Lighting Equipment',            'Measurable'),
  ('Mobile Water Tanker',                'Water, Fuel & Lighting Equipment','Water Equipment',               'Measurable'),
  ('Towable Tower Light - Solar',        'Water, Fuel & Lighting Equipment','Lighting Equipment',            'Non-Measurable')
ON CONFLICT (name) DO UPDATE SET
  asset_group    = EXCLUDED.asset_group,
  asset_cat      = EXCLUDED.asset_cat,
  asset_category = COALESCE(EXCLUDED.asset_category, equipment_types.asset_category);
