-- Seed asset_matrix with 867 unique make+model combinations
-- Collapsed from ERP export: same make+model = one AM ID regardless of capacity
INSERT INTO asset_matrix (am_id, asset_type, manufacturer, model, fuel_type)
VALUES
  ('RVR-AM-00001', 'All Terrain Crane - HR & KM Based', 'Krupp Cranes', 'KMK 4070', 'HS Diesel'),
  ('RVR-AM-00002', 'All Terrain Crane - HR & KM Based', 'Sany Heavy Industry', 'SAC7000T7', 'HS Diesel'),
  ('RVR-AM-00003', 'Asphalt Batch Mix Plant', 'Speco Limited', 'TSAP-2000 FFW', NULL),
  ('RVR-AM-00004', 'Asphalt Batch Mix Plant', 'AMMANN', 'ABC-120', NULL),
  ('RVR-AM-00005', 'Asphalt Batch Mix Plant', 'MARINI S.p.A.', 'MAC 160', NULL),
  ('RVR-AM-00006', 'Asphalt Batch Mix Plant', 'D&G Machinery', 'DG3000T250', NULL),
  ('RVR-AM-00007', 'Asphalt Batch Mix Plant', 'Vibrant Construction Equipment', 'VBA-180', NULL),
  ('RVR-AM-00008', 'Asphalt Paver - Track', 'VOGELE', 'Super 1800-3', 'HS Diesel'),
  ('RVR-AM-00009', 'Asphalt Paver - Track', 'VOGELE', 'Super 1800-2', 'HS Diesel'),
  ('RVR-AM-00010', 'Asphalt Paver - Track', 'VOGELE', 'Super 1800-1', 'HS Diesel'),
  ('RVR-AM-00011', 'Asphalt Paver - Track', 'VOGELE', 'S1400i', 'HS Diesel'),
  ('RVR-AM-00012', 'Automatic Stirrup Bending Machine', 'MEP Group', 'F13', NULL),
  ('RVR-AM-00013', 'Backhoe Loader', 'JCB India Limited', '3DX Super', 'HS Diesel'),
  ('RVR-AM-00014', 'Backhoe Loader', 'Caterpillar India Private Limited', '424B', 'HS Diesel'),
  ('RVR-AM-00015', 'Backhoe Loader', 'Case New Holland CE', '770 EX', 'HS Diesel'),
  ('RVR-AM-00016', 'Backhoe Loader', 'Mahindra Construction Equipment', 'EarthMaster SX', 'HS Diesel'),
  ('RVR-AM-00017', 'Backhoe Loader', 'Action Construction Equipment', 'AX 130', 'HS Diesel'),
  ('RVR-AM-00018', 'Backhoe Loader', 'Tata Hitachi - TELCON', '315 V', 'HS Diesel'),
  ('RVR-AM-00019', 'Backhoe Loader', 'Caterpillar India Private Limited', '424 B2', 'HS Diesel'),
  ('RVR-AM-00020', 'Backhoe Loader', 'Tata Hitachi - TELCON', 'Shinrai', 'HS Diesel'),
  ('RVR-AM-00021', 'Backhoe Loader', 'Bull Machines', 'BULL HD76', 'HS Diesel'),
  ('RVR-AM-00022', 'Backhoe Loader', 'JCB India Limited', '3DX', 'HS Diesel'),
  ('RVR-AM-00023', 'BAG SLITTING MACHINE', 'NMF Equipments', 'NMF 18- CDF2515', NULL),
  ('RVR-AM-00024', 'Bar Bending Machine', 'Spantech Engineering', 'SB 42', NULL),
  ('RVR-AM-00025', 'Bar Bending Machine', 'Spartan Engineering', 'SBM 55V', NULL),
  ('RVR-AM-00026', 'Bar Bending Machine', 'Spartan Engineering', 'SBM 52V', NULL),
  ('RVR-AM-00027', 'Bar Bending Machine', 'Spartan Engineering', 'SBM 42V', NULL),
  ('RVR-AM-00028', 'Bar Bending Machine', 'Jaypee India Limited', 'B55', NULL),
  ('RVR-AM-00029', 'Bar Bending Machine', 'Acme Concrete Mixers', 'BBM 40', NULL),
  ('RVR-AM-00030', 'Bar Bending Machine', 'Universal Construction', 'UBM42', NULL),
  ('RVR-AM-00031', 'Bar Bending Machine', 'Jaypee India Limited', 'RB42', NULL),
  ('RVR-AM-00032', 'Bar Bending Machine', 'Innomac Engineering', 'IBM52', NULL),
  ('RVR-AM-00033', 'Bar Bending Machine', 'Unimaac Engineers', 'GW 50', NULL),
  ('RVR-AM-00034', 'Bar Bending Machine', 'Local Manufacturer', 'Unknown', NULL),
  ('RVR-AM-00035', 'Bar Bending Machine', 'Innomac Engineering', 'IBM 55', NULL),
  ('RVR-AM-00036', 'Bar Bending Machine', 'Skipper Construction Equipment', 'SKB 55', NULL),
  ('RVR-AM-00037', 'Bar Bending Machine', 'Spartech Impex', 'GW-42J', NULL),
  ('RVR-AM-00038', 'Bar Bending Machine', 'Universal Construction', 'UBM55', NULL),
  ('RVR-AM-00039', 'Bar Cutting Machine', 'Spartan Engineering', 'SCM 42', NULL),
  ('RVR-AM-00040', 'Bar Cutting Machine', 'Spartan Engineering', 'SCM 52', NULL),
  ('RVR-AM-00041', 'Bar Cutting Machine', 'Spartan Engineering', 'SCM 55', NULL),
  ('RVR-AM-00042', 'Bar Cutting Machine', 'Universal Construction', 'UCM42', NULL),
  ('RVR-AM-00043', 'Bar Cutting Machine', 'Acme Concrete Mixers', 'BCM 40', NULL),
  ('RVR-AM-00044', 'Bar Cutting Machine', 'Unimaac Engineers', 'GQ50', NULL),
  ('RVR-AM-00045', 'Bar Cutting Machine', 'Innomac Engineering', 'ICM 52', NULL),
  ('RVR-AM-00046', 'Bar Cutting Machine', 'Innomac Engineering', 'ICM 55', NULL),
  ('RVR-AM-00047', 'Bar Cutting Machine', 'Spartan Engineering', 'SCM 55V', NULL),
  ('RVR-AM-00048', 'Bar Cutting Machine', 'Atg Manufacturing', 'ATG 232', NULL),
  ('RVR-AM-00049', 'Bar Cutting Machine', 'Skipper Construction Equipment', 'SKC 55', NULL),
  ('RVR-AM-00050', 'Bar Cutting Machine', 'Spartech Impex', 'GQ-42', NULL),
  ('RVR-AM-00051', 'Bar Cutting Machine', 'Universal Construction', 'UCM52', NULL),
  ('RVR-AM-00052', 'Bar Cutting Machine', 'Universal Construction', 'UCM55', NULL),
  ('RVR-AM-00053', 'Bar Decoiler and Cutting Machine', 'Jaypee India Limited', 'ST-14', NULL),
  ('RVR-AM-00054', 'Bar Decoiler and Cutting Machine', 'Innomac Engineering', 'ISSM-12', NULL),
  ('RVR-AM-00055', 'Bitumen Sprayer', 'Ashok Leyland', '1615 HE', 'HS Diesel'),
  ('RVR-AM-00056', 'Brick Molding Machine', 'Hycon Machines', 'Hybrick 1600', NULL),
  ('RVR-AM-00057', 'Brick Molding Machine', 'Mega Engineering', 'Mega', NULL),
  ('RVR-AM-00058', 'Brick Molding Machine', 'Tara Machines', 'MechRam X1250', NULL),
  ('RVR-AM-00059', 'Brick Molding Machine', 'GAURAV MACHINE TOOLS', 'GMT03', NULL),
  ('RVR-AM-00060', 'Brick Molding Machine', 'Global Impex', 'SS-WR-W4A', NULL),
  ('RVR-AM-00061', 'Brick Molding Machine', 'Mahavir Industries', 'CMF8', NULL),
  ('RVR-AM-00062', 'Brick Molding Machine', 'J K Tiles Machinery', 'COL 150 / CMS 300', NULL),
  ('RVR-AM-00063', 'Bucket Crusher', 'MB Crusher', 'BF90.3 S4', NULL),
  ('RVR-AM-00064', 'Builder Hoist', 'Innomac Engineering', 'IMH 1500', NULL),
  ('RVR-AM-00065', 'Builder Hoist', 'Jaypee India Limited', 'JCH 1000', NULL),
  ('RVR-AM-00066', 'Builder Hoist', 'Siemens India', '800K', NULL),
  ('RVR-AM-00067', 'Builder Hoist', 'Vikrant Cranes', '1 Ton', NULL),
  ('RVR-AM-00068', 'Builder Hoist', 'Skipper Construction Equipment', 'STH-150', NULL),
  ('RVR-AM-00069', 'Bus', 'Eicher Motors Limited', '10.75 H', 'HS Diesel'),
  ('RVR-AM-00070', 'Bus', 'Tata Motors Limited', 'Star 410', 'HS Diesel'),
  ('RVR-AM-00071', 'Bus', 'Ashok Leyland', 'Stag ALFBV1/7', 'HS Diesel'),
  ('RVR-AM-00072', 'Bus', 'Force Motors', 'Bus 4020', 'HS Diesel'),
  ('RVR-AM-00073', 'Bus', 'Eicher Motors Limited', '10.75 E', 'HS Diesel'),
  ('RVR-AM-00074', 'Bus', 'Ashok Leyland', 'ALPSV3/56', 'HS Diesel'),
  ('RVR-AM-00075', 'Bus', 'Tata Motors Limited', 'Star Bus LP812/52', 'HS Diesel'),
  ('RVR-AM-00076', 'Bus', 'Tata Motors Limited', 'Star Bus LP412/36', 'HS Diesel'),
  ('RVR-AM-00077', 'Bus', 'Tata Motors Limited', 'Star Bus LP410/36', 'HS Diesel'),
  ('RVR-AM-00078', 'Bus', 'Ashok Leyland', 'SS1008.104RB', 'HS Diesel'),
  ('RVR-AM-00079', 'Car', 'Honda Cars', 'City', 'HS Diesel'),
  ('RVR-AM-00080', 'Car', 'Maruti Suzuki', 'Brezza', 'HS Diesel'),
  ('RVR-AM-00081', 'Car', 'Hyundai Cars', 'Creta', 'HS Diesel'),
  ('RVR-AM-00082', 'Car', 'Mercedes Benz India', 'E220', 'HS Diesel'),
  ('RVR-AM-00083', 'Car', 'Maruti Suzuki', 'Swift Dzire', 'HS Diesel'),
  ('RVR-AM-00084', 'Car', 'Volkswagen India', 'Vento', 'Petrol'),
  ('RVR-AM-00085', 'Car', 'Mercedes Benz India', 'E200', 'Petrol'),
  ('RVR-AM-00086', 'Car', 'Mercedes Benz India', 'GLC 43', 'Petrol'),
  ('RVR-AM-00087', 'Car', 'Mercedes Benz India', 'SLK-350', 'Petrol'),
  ('RVR-AM-00088', 'Car', 'Audi India', 'R8', 'Petrol'),
  ('RVR-AM-00089', 'Car', 'BMW India', 'X 3', 'HS Diesel'),
  ('RVR-AM-00090', 'Car', 'Tata Motors Limited', 'NEXON ZX+', 'HS Diesel'),
  ('RVR-AM-00091', 'Car', 'KIA Motors', 'Seltos', 'HS Diesel'),
  ('RVR-AM-00092', 'Car', 'Mahindra and Mahindra Limited', 'BOLERO NEO', 'HS Diesel'),
  ('RVR-AM-00093', 'Car', 'Chevrolet', 'Tavera', 'HS Diesel'),
  ('RVR-AM-00094', 'Car', 'Mahindra and Mahindra Limited', 'Bolero Neo N10', 'HS Diesel'),
  ('RVR-AM-00095', 'Car', 'BMW India', 'X7', 'HS Diesel'),
  ('RVR-AM-00096', 'Car', 'Volvo India Private Limited', 'XC 90 D5', 'HS Diesel'),
  ('RVR-AM-00097', 'Car', 'Maruti Suzuki', 'WagonR', 'CNG'),
  ('RVR-AM-00098', 'Car', 'JAGUAR LAND ROVER LIMITED', 'RANGE ROVER EVOQUE', 'Petrol'),
  ('RVR-AM-00099', 'Car', 'Ford Motor Company', 'Endeavour 2.0L', 'HS Diesel'),
  ('RVR-AM-00100', 'Car', 'Tata Motors Limited', 'Hexa', 'HS Diesel'),
  ('RVR-AM-00101', 'Car', 'Toyota Kirloskar Motor', 'Innova HyCross', 'HS Diesel'),
  ('RVR-AM-00102', 'Car', 'Mahindra and Mahindra Limited', 'XUV 700', 'HS Diesel'),
  ('RVR-AM-00103', 'Car', 'Mercedes Benz India', 'GLE 300D', 'HS Diesel'),
  ('RVR-AM-00104', 'Car', 'Rolls-Royce Motor', 'Phantom', 'Petrol'),
  ('RVR-AM-00105', 'Car', 'Porsche Automobil', 'Macan', 'HS Diesel'),
  ('RVR-AM-00106', 'Cement Screw Pump', 'NMF Equipments', 'SCP 150', NULL),
  ('RVR-AM-00107', 'Cement Screw Pump', 'NMF Equipments', 'SCP 220', NULL),
  ('RVR-AM-00108', 'Cement Screw Pump', 'NMF Equipments', 'SCP 225', NULL),
  ('RVR-AM-00109', 'Cement Screw Pump', 'NMF Equipments', 'SCP150 1822 TPH', NULL),
  ('RVR-AM-00110', 'Cement Screw Pump', 'NMF Equipments', 'NMF 230A/B', NULL),
  ('RVR-AM-00111', 'Cement Screw Pump', 'NMF Equipments', 'NMF1200', NULL),
  ('RVR-AM-00112', 'Cement Screw Pump', 'TMVT Industries', 'MTLK 150', NULL),
  ('RVR-AM-00113', 'Cement Screw Pump', 'Airvac Industries', 'DGR-221', NULL),
  ('RVR-AM-00114', 'Cement Screw Pump', 'Schwing Stetter India', 'PBL-CFM-50', NULL),
  ('RVR-AM-00115', 'Cement Screw Pump', 'NMF Equipments', 'PBL-CFM-50', NULL),
  ('RVR-AM-00116', 'Chiller Plant', 'Reynold India', 'Screw Chiller', NULL),
  ('RVR-AM-00117', 'Chiller Plant', 'Schwing Stetter India', 'ACWC-TC-35TR', NULL),
  ('RVR-AM-00118', 'Chip Spreader', 'Himakshi Equipments', '600 X 12', NULL),
  ('RVR-AM-00119', 'CNC Cutting Machine', 'Primo Automation Systems', 'PLASMA CUTTING', NULL),
  ('RVR-AM-00120', 'CNC Plate Drilling Machine', 'Primo Automation Systems', '40MM', NULL),
  ('RVR-AM-00121', 'Compressor Machine', 'Ingersoll Rand India Limited', '2545', NULL),
  ('RVR-AM-00122', 'Compressor Machine', 'Elgi Equipments Limited', 'TS05 120HN', NULL),
  ('RVR-AM-00123', 'Compressor Machine', 'Elgi Equipments Limited', 'LG02 100', NULL),
  ('RVR-AM-00124', 'Compressor Machine', 'Elgi Equipments Limited', 'TS07 120HN', NULL),
  ('RVR-AM-00125', 'Compressor Machine', 'Elgi Equipments Limited', 'TS10 120HN', NULL),
  ('RVR-AM-00126', 'Compressor Machine', 'Anest Iwata Motherson', 'TLT50C-12-18E', NULL),
  ('RVR-AM-00127', 'Compressor Machine', 'Elgi Equipments Limited', '2545', NULL),
  ('RVR-AM-00128', 'Concrete Batching Plant', 'Schwing Stetter India', 'CP 18', NULL),
  ('RVR-AM-00129', 'Concrete Batching Plant', 'Schwing Stetter India', 'M1C', NULL),
  ('RVR-AM-00130', 'Concrete Batching Plant', 'Schwing Stetter India', 'HN 4.0', NULL),
  ('RVR-AM-00131', 'Concrete Batching Plant', 'Schwing Stetter India', 'CP 30', NULL),
  ('RVR-AM-00132', 'Concrete Batching Plant', 'Schwing Stetter India', 'M 2.5', NULL),
  ('RVR-AM-00133', 'Concrete Batching Plant', 'Schwing Stetter India', 'M30 Z', NULL),
  ('RVR-AM-00134', 'Concrete Batching Plant', 'Simem India', 'MobiMix 1500', NULL),
  ('RVR-AM-00135', 'Concrete Batching Plant', 'Macons Equipments', 'MA-15', NULL),
  ('RVR-AM-00136', 'Concrete Batching Plant', 'Schwing Stetter India', 'M1T', NULL),
  ('RVR-AM-00137', 'Concrete Batching Plant', 'KYB Conmat', 'CRP 600', NULL),
  ('RVR-AM-00138', 'Concrete Batching Plant', 'Ajax Fiori', 'Ambison 756', NULL),
  ('RVR-AM-00139', 'Concrete Batching Plant', 'AMMANN', 'CC 30', NULL),
  ('RVR-AM-00140', 'Concrete Batching Plant', 'Schwing Stetter India', 'M3E', NULL),
  ('RVR-AM-00141', 'Concrete Batching Plant', 'AMMANN', 'CC60 ELBA', NULL),
  ('RVR-AM-00142', 'Concrete Batching Plant', 'Vibrant Construction Equipment', 'SCP60', NULL),
  ('RVR-AM-00143', 'Concrete Batching Plant', 'Putzmeister Concrete Machines', 'MT 1.0', NULL),
  ('RVR-AM-00144', 'Concrete Block Machine', 'QUNFENG', 'QTF515', NULL),
  ('RVR-AM-00145', 'Concrete Block Machine', 'Little Block Engineers Enterprises', 'EE003', NULL),
  ('RVR-AM-00146', 'Concrete Mixer - Engine Driven', 'Others', 'Others', 'HS Diesel'),
  ('RVR-AM-00147', 'Concrete Mixer - Engine Driven', 'Esquare Machines', 'EMH 300D HF', 'HS Diesel'),
  ('RVR-AM-00148', 'Concrete Mixer - Motor Driven', 'Gamzen Plast', '750RM', NULL),
  ('RVR-AM-00149', 'Concrete Mixer - Motor Driven', 'Universal Construction', 'RM 800', NULL),
  ('RVR-AM-00150', 'Concrete Mixer - Motor Driven', 'Acme Concrete Mixers', 'RM800', NULL),
  ('RVR-AM-00151', 'Concrete Pump', 'Putzmeister Concrete Machines', 'BSA 1407D', 'HS Diesel'),
  ('RVR-AM-00152', 'Concrete Pump', 'Schwing Stetter India', 'SP1400', 'HS Diesel'),
  ('RVR-AM-00153', 'Concrete Pump', 'Schwing Stetter India', 'SP1800', 'HS Diesel'),
  ('RVR-AM-00154', 'Concrete Pump', 'Putzmeister Concrete Machines', 'BSA 1405D', 'HS Diesel'),
  ('RVR-AM-00155', 'Concrete Pump', 'Schwing Stetter India', 'BP 350 D', 'HS Diesel'),
  ('RVR-AM-00156', 'Concrete Pump', 'Putzmeister Concrete Machines', 'BSA 1404 HD', 'HS Diesel'),
  ('RVR-AM-00157', 'Concrete Pump', 'Schwing Stetter India', 'BP 1800', 'HS Diesel'),
  ('RVR-AM-00158', 'Concrete Pump', 'Putzmeister Concrete Machines', 'BSA 1410 D', 'HS Diesel'),
  ('RVR-AM-00159', 'Concrete Pump', 'Schwing Stetter India', 'BP2800', 'HS Diesel'),
  ('RVR-AM-00160', 'Concrete Pump', 'Greaves Infra', '350D', 'HS Diesel'),
  ('RVR-AM-00161', 'Concrete Pump', 'Putzmeister Concrete Machines', 'BSA 1407 HD', 'HS Diesel'),
  ('RVR-AM-00162', 'Concrete Pump - Motor Driven', 'Schwing Stetter India', 'SP 3500 E', NULL),
  ('RVR-AM-00163', 'Concrete Pump - Motor Driven', 'Schwing Stetter India', 'BP 350 EXT', NULL),
  ('RVR-AM-00164', 'Concrete Pump - Motor Driven', 'Schwing Stetter India', 'SP 1200 E', NULL),
  ('RVR-AM-00165', 'CONCRETE RECYCLING PLANT', 'Schwing Stetter India', 'RA 6', NULL),
  ('RVR-AM-00166', 'Cone Crusher - Stationary', 'Puzzolana Machinery Fabricators', '1992', NULL),
  ('RVR-AM-00167', 'Cone Crusher - Stationary', 'Metso India', 'Cone-GP11F', NULL),
  ('RVR-AM-00168', 'Cone Crusher - Stationary', 'Metso India', 'HP 200', NULL),
  ('RVR-AM-00169', 'Cone Crusher - Stationary', 'MachineTech Engineering', 'UC1300', NULL),
  ('RVR-AM-00170', 'Cone Crusher - Stationary', 'Metso India', 'Nordberg HP300', NULL),
  ('RVR-AM-00171', 'Cone Crusher - Stationary', 'MachineTech Engineering', 'ULTRA CONE UC1300', NULL),
  ('RVR-AM-00172', 'Cone Crusher - Wheel Mounted', 'Metso India', 'GP220', NULL),
  ('RVR-AM-00173', 'Crawler Crane', 'Sany Heavy Industry', 'SCC 2500', 'HS Diesel'),
  ('RVR-AM-00174', 'Crawler Crane', 'Tata Motors Limited', 'TFC 280', 'HS Diesel'),
  ('RVR-AM-00175', 'Crawler Crane', 'Kobelco CE', 'CKE1000i', 'HS Diesel'),
  ('RVR-AM-00176', 'Crawler Crane', 'Zoomlion India', 'QUY 70', 'HS Diesel'),
  ('RVR-AM-00177', 'Crawler Crane', 'Fushun Corporation', 'QUY 35', 'HS Diesel'),
  ('RVR-AM-00178', 'Crawler Crane', 'Tata Hitachi - TELCON', 'TFC 75', 'HS Diesel'),
  ('RVR-AM-00179', 'Crawler Crane', 'XCMG', 'XGC 55', 'HS Diesel'),
  ('RVR-AM-00180', 'Crawler Crane', 'Sany Heavy Industry', 'SCC 1500A', 'HS Diesel'),
  ('RVR-AM-00181', 'Crawler Crane', 'Liebherr India Private Limited', 'LR 1400/2', 'HS Diesel'),
  ('RVR-AM-00182', 'Crawler Crane', 'Sany Heavy Industry', 'SCC 600A', 'HS Diesel'),
  ('RVR-AM-00183', 'Crawler Crane', 'XCMG', 'XCG 80 - I', 'HS Diesel'),
  ('RVR-AM-00184', 'Crawler Crane', 'XCMG', 'QUY 300', 'HS Diesel'),
  ('RVR-AM-00185', 'Crawler Crane', 'Sany Heavy Industry', 'SCS600A', 'HS Diesel'),
  ('RVR-AM-00186', 'Dozer', 'Caterpillar India Private Limited', 'D6G', 'HS Diesel'),
  ('RVR-AM-00187', 'Dozer', 'BEML', 'BD65-1', 'HS Diesel'),
  ('RVR-AM-00188', 'Dozer', 'BEML', 'BD 50', 'HS Diesel'),
  ('RVR-AM-00189', 'Dozer', 'Caterpillar India Private Limited', 'D5C III', 'HS Diesel'),
  ('RVR-AM-00190', 'Dozer', 'BEML', 'BD355', 'HS Diesel'),
  ('RVR-AM-00191', 'Dozer', 'Komatsu India Private Limited', 'D85ESS-2', 'HS Diesel'),
  ('RVR-AM-00192', 'Dozer', 'Caterpillar India Private Limited', 'D4D', 'HS Diesel'),
  ('RVR-AM-00193', 'Dozer', 'BEML', 'BD80', 'HS Diesel'),
  ('RVR-AM-00194', 'Dozer', 'BEML', 'BD85', 'HS Diesel'),
  ('RVR-AM-00195', 'Drill Jumbo Rig', 'Sandvik Asia', 'DT820', 'HS Diesel'),
  ('RVR-AM-00196', 'Drill Jumbo Rig', 'Atlas Copco India Limited', 'L2D', 'HS Diesel'),
  ('RVR-AM-00197', 'Drill Jumbo Rig', 'Epiroc India', 'L2D Boomer - 1838HD', 'HS Diesel'),
  ('RVR-AM-00198', 'Drill Jumbo Rig', 'Sandvik Asia', 'DT1130', 'HS Diesel'),
  ('RVR-AM-00199', 'Electric Mini Truck', 'Tata Motors Limited', 'ACE EV', NULL),
  ('RVR-AM-00200', 'Engine Driven Bar Cutting Machine', 'Greaves Cotton Limited', '1510', 'HS Diesel'),
  ('RVR-AM-00201', 'EOT Crane', 'AP Cranes', '30 MTR SPAN', NULL),
  ('RVR-AM-00202', 'EOT Crane', 'GRIP Engineers', '20 TON', NULL),
  ('RVR-AM-00203', 'EOT Crane', 'GRIP Engineers', '8 Ton', NULL),
  ('RVR-AM-00204', 'Excavator', 'Kobelco CE', 'SK210 HD', 'HS Diesel'),
  ('RVR-AM-00205', 'Excavator', 'Hyundai CE', 'R220 L', 'HS Diesel'),
  ('RVR-AM-00206', 'Excavator', 'Komatsu India Private Limited', 'PC200', 'HS Diesel'),
  ('RVR-AM-00207', 'Excavator', 'Komatsu India Private Limited', 'PC210', 'HS Diesel'),
  ('RVR-AM-00208', 'Excavator', 'Hyundai CE', 'R 210 V', 'HS Diesel'),
  ('RVR-AM-00209', 'Excavator', 'Hyundai CE', 'R 210', 'HS Diesel'),
  ('RVR-AM-00210', 'Excavator', 'Tata Hitachi - TELCON', 'EX200', 'HS Diesel'),
  ('RVR-AM-00211', 'Excavator', 'Tata Hitachi - TELCON', 'EX70', 'HS Diesel'),
  ('RVR-AM-00212', 'Excavator', 'Tata Hitachi - TELCON', 'EX 110', 'HS Diesel'),
  ('RVR-AM-00213', 'Excavator', 'JCB India Limited', 'JS 140', 'HS Diesel'),
  ('RVR-AM-00214', 'Excavator', 'JCB India Limited', 'JS 205', 'HS Diesel'),
  ('RVR-AM-00215', 'Excavator', 'Hyundai CE', 'R140 LC', 'HS Diesel'),
  ('RVR-AM-00216', 'Excavator', 'Hyundai CE', 'R215 LC', 'HS Diesel'),
  ('RVR-AM-00217', 'Excavator', 'Sany Heavy Industry', 'SY210 C', 'HS Diesel'),
  ('RVR-AM-00218', 'Excavator', 'Tata Hitachi - TELCON', 'EX210 LC', 'HS Diesel'),
  ('RVR-AM-00219', 'Excavator', 'JCB India Limited', 'JS220 LC', 'HS Diesel'),
  ('RVR-AM-00220', 'Excavator', 'Kobelco CE', 'SK380 XDLC', 'HS Diesel'),
  ('RVR-AM-00221', 'Excavator', 'Volvo India Private Limited', 'EC 480DL', 'HS Diesel'),
  ('RVR-AM-00222', 'Excavator', 'Sany Heavy Industry', 'SY215C', 'HS Diesel'),
  ('RVR-AM-00223', 'Excavator', 'Volvo India Private Limited', 'EC240', 'HS Diesel'),
  ('RVR-AM-00224', 'Excavator', 'Doosan Infracore', 'DX210LC', 'HS Diesel'),
  ('RVR-AM-00225', 'Excavator', 'Kobelco CE', 'SK220 XDLC', 'HS Diesel'),
  ('RVR-AM-00226', 'Excavator', 'Volvo India Private Limited', 'EC210D', 'HS Diesel'),
  ('RVR-AM-00227', 'Excavator', 'Hyundai CE', 'R210 - 7', 'HS Diesel'),
  ('RVR-AM-00228', 'Excavator', 'Hyundai CE', 'R215L SMART+', 'HS Diesel'),
  ('RVR-AM-00229', 'Excavator', 'Caterpillar India Private Limited', '320D3 GC', 'HS Diesel'),
  ('RVR-AM-00230', 'Excavator', 'Caterpillar India Private Limited', '320D3', 'HS Diesel'),
  ('RVR-AM-00231', 'Excavator', 'Tata Hitachi - TELCON', 'ZAXIS 470H', 'HS Diesel'),
  ('RVR-AM-00232', 'Excavator', 'JCB India Limited', 'NXT 215LC', 'HS Diesel'),
  ('RVR-AM-00233', 'Excavator', 'Liugong India', '926E XD', 'HS Diesel'),
  ('RVR-AM-00234', 'Excavator', 'Liugong India', '922 E', 'HS Diesel'),
  ('RVR-AM-00235', 'Excavator', 'JCB India Limited', 'JS 210 LC', 'HS Diesel'),
  ('RVR-AM-00236', 'Excavator', 'JCB India Limited', 'NXT 225LC', 'HS Diesel'),
  ('RVR-AM-00237', 'Excavator', 'Kobelco CE', 'SK220 XDLC-10', 'HS Diesel'),
  ('RVR-AM-00238', 'Excavator', 'Tata Hitachi - TELCON', 'EX200 Super Plus', 'HS Diesel'),
  ('RVR-AM-00239', 'Excavator', 'Sany Heavy Industry', 'SY245C', 'HS Diesel'),
  ('RVR-AM-00240', 'Excavator', 'JCB India Limited', 'JS-215LC', 'HS Diesel'),
  ('RVR-AM-00241', 'Excavator', 'XCMG', 'XE220C', 'HS Diesel'),
  ('RVR-AM-00242', 'Excavator', 'Tata Hitachi - TELCON', '220LC GI', 'HS Diesel'),
  ('RVR-AM-00243', 'Excavator', 'Tata Hitachi - TELCON', 'EX 215LC', 'HS Diesel'),
  ('RVR-AM-00244', 'Excavator', 'XCMG', 'XE 210i', 'HS Diesel'),
  ('RVR-AM-00245', 'Excavator', 'Komatsu India Private Limited', 'PC205-10M0', 'HS Diesel'),
  ('RVR-AM-00246', 'Excavator', 'XCMG', 'XE215L', 'HS Diesel'),
  ('RVR-AM-00247', 'Fixed Form Paver - Motor Driven', 'KYB Conmat', 'CE 200', NULL),
  ('RVR-AM-00248', 'Flange Straightening Machine', 'Primo Automation Systems', '350-1200MM', NULL),
  ('RVR-AM-00249', 'Fork Lift', 'Godrej Material Handling', 'GX300 DC', 'HS Diesel'),
  ('RVR-AM-00250', 'Fork Lift', 'KION India', 'DVX 506 AT', 'HS Diesel'),
  ('RVR-AM-00251', 'Gantry Crane - Without Genset', 'SV Material Handling', '20T', NULL),
  ('RVR-AM-00252', 'Gantry Crane - Without Genset', 'SV Material Handling', '60T', NULL),
  ('RVR-AM-00253', 'Gantry Crane - Without Genset', 'AP Cranes', '60T', NULL),
  ('RVR-AM-00254', 'Gantry Crane - Without Genset', 'AP Cranes', '8T', NULL),
  ('RVR-AM-00255', 'Gantry Crane - Without Genset', 'Alpha Services', '100 MT', NULL),
  ('RVR-AM-00256', 'Gantry Crane - Without Genset', 'Alpha Services', '90 MT', NULL),
  ('RVR-AM-00257', 'Gantry Crane - Without Genset', 'AP Cranes', '100T', NULL),
  ('RVR-AM-00258', 'Gantry Crane - Without Genset', 'Alpha Services', '80 MT', NULL),
  ('RVR-AM-00259', 'Gantry Crane - Without Genset', 'Alpha Services', '75 MT', NULL),
  ('RVR-AM-00260', 'Gantry Crane - Without Genset', 'AP Cranes', '20T', NULL),
  ('RVR-AM-00261', 'Gantry Crane - Without Genset', 'SV Material Handling', '65MT', NULL),
  ('RVR-AM-00262', 'Gantry Crane - Without Genset', 'Electromech Material Handling', '20T', NULL),
  ('RVR-AM-00263', 'Gantry Crane - Without Genset', 'Electromech Material Handling', '75T', NULL),
  ('RVR-AM-00264', 'Gantry Crane - Without Genset', 'Sureka Teknik', '65T', NULL),
  ('RVR-AM-00265', 'Gantry Crane - Without Genset', 'Redson Engineers', '25MT', NULL),
  ('RVR-AM-00266', 'Gantry Crane - Without Genset', 'Cisco-Eagle', '20T', NULL),
  ('RVR-AM-00267', 'Gantry Crane - Without Genset', 'Alpha Services', '20 MT', NULL),
  ('RVR-AM-00268', 'Gantry Crane - Without Genset', 'AP Cranes', '25/5T', NULL),
  ('RVR-AM-00269', 'Gantry Crane - Without Genset', 'AP Cranes', '120/15', NULL),
  ('RVR-AM-00270', 'Gantry Crane - Without Genset', 'AP Cranes', '120/10', NULL),
  ('RVR-AM-00271', 'Genset', 'Kirloskar Oil Engines Limited', '3R1040 G1', 'HS Diesel'),
  ('RVR-AM-00272', 'Genset', 'Kirloskar Oil Engines Limited', '6SL8800TA', 'HS Diesel'),
  ('RVR-AM-00273', 'Genset', 'Kirloskar Oil Engines Limited', '4R1040TA', 'HS Diesel'),
  ('RVR-AM-00274', 'Genset', 'Kirloskar Oil Engines Limited', 'RV2', 'HS Diesel'),
  ('RVR-AM-00275', 'Genset', 'Cummins India Limited', 'C 250 D5P', 'HS Diesel'),
  ('RVR-AM-00276', 'Genset', 'Cummins India Limited', 'C 200 D5P', 'HS Diesel'),
  ('RVR-AM-00277', 'Genset', 'Cummins India Limited', 'C 160 D5P', 'HS Diesel'),
  ('RVR-AM-00278', 'Genset', 'Cummins India Limited', 'C 125 D5P', 'HS Diesel'),
  ('RVR-AM-00279', 'Genset', 'Cummins India Limited', 'C 100 D5P', 'HS Diesel'),
  ('RVR-AM-00280', 'Genset', 'Cummins India Limited', 'C 82.5 D5P', 'HS Diesel'),
  ('RVR-AM-00281', 'Genset', 'Cummins India Limited', 'C 62.5 D5P', 'HS Diesel'),
  ('RVR-AM-00282', 'Genset', 'Cummins India Limited', 'C 40 D5P', 'HS Diesel'),
  ('RVR-AM-00283', 'Genset', 'Cummins India Limited', 'C 30 D5P', 'HS Diesel'),
  ('RVR-AM-00284', 'Genset', 'Cummins India Limited', 'C 320 D5P', 'HS Diesel'),
  ('RVR-AM-00285', 'Genset', 'Cummins India Limited', 'C 20 D5P', 'HS Diesel'),
  ('RVR-AM-00286', 'Genset', 'Cummins India Limited', 'C 500 D5P', 'HS Diesel'),
  ('RVR-AM-00287', 'Genset', 'Mahindra and Mahindra Limited', '4445', 'HS Diesel'),
  ('RVR-AM-00288', 'Genset', 'Kirloskar Oil Engines Limited', '6R1080TA', 'HS Diesel'),
  ('RVR-AM-00289', 'Genset', 'Mahindra and Mahindra Limited', 'Prime 40', 'HS Diesel'),
  ('RVR-AM-00290', 'Genset', 'Cummins India Limited', 'C380 D5P', 'HS Diesel'),
  ('RVR-AM-00291', 'Genset', 'Cummins India Limited', 'C180 D5P', 'HS Diesel'),
  ('RVR-AM-00292', 'Genset', 'Cummins India Limited', 'C 400 D5P', 'HS Diesel'),
  ('RVR-AM-00293', 'Genset', 'Cummins India Limited', 'C600D5P', 'HS Diesel'),
  ('RVR-AM-00294', 'Genset', 'Cummins India Limited', 'C45D5P', 'HS Diesel'),
  ('RVR-AM-00295', 'Genset', 'Cummins India Limited', 'C35D5P', 'HS Diesel'),
  ('RVR-AM-00296', 'Genset', 'Cummins India Limited', 'C25D5P', 'HS Diesel'),
  ('RVR-AM-00297', 'Genset', 'Cummins India Limited', 'C15D5P', 'HS Diesel'),
  ('RVR-AM-00298', 'Genset', 'Caterpillar India Private Limited', '3412 DITA-GP-3', 'HS Diesel'),
  ('RVR-AM-00299', 'Genset', 'Caterpillar India Private Limited', 'C 18', 'HS Diesel'),
  ('RVR-AM-00300', 'Genset', 'Caterpillar India Private Limited', 'C 15', 'HS Diesel'),
  ('RVR-AM-00301', 'Genset', 'Greaves Cotton Limited', 'GPWII-500', 'HS Diesel'),
  ('RVR-AM-00302', 'Genset', 'Greaves Cotton Limited', 'GPWII-400', 'HS Diesel'),
  ('RVR-AM-00303', 'Genset', 'Cummins India Limited', 'C380D5P', 'HS Diesel'),
  ('RVR-AM-00304', 'Genset', 'Caterpillar India Private Limited', '3406 DITA-GP-2', 'HS Diesel'),
  ('RVR-AM-00305', 'Genset', 'Ashok Leyland', 'LP62.5D1', 'HS Diesel'),
  ('RVR-AM-00306', 'Genset', 'Kirloskar Oil Engines Limited', 'HA494', 'HS Diesel'),
  ('RVR-AM-00307', 'Genset', 'Ashok Leyland', 'LP125D', 'HS Diesel'),
  ('RVR-AM-00308', 'Genset', 'Kirloskar Oil Engines Limited', 'EA10', 'HS Diesel'),
  ('RVR-AM-00309', 'Genset', 'Kirloskar Oil Engines Limited', 'EA16', 'HS Diesel'),
  ('RVR-AM-00310', 'Genset', 'Elmot Powergen', 'ELM-62p5', 'HS Diesel'),
  ('RVR-AM-00311', 'Genset', 'Elmot Powergen', 'ELM-125', 'HS Diesel'),
  ('RVR-AM-00312', 'Genset', 'Cummins India Limited', 'C 50 D5P', 'HS Diesel'),
  ('RVR-AM-00313', 'Genset', 'Eicher Motors Limited', '323 ES', 'HS Diesel'),
  ('RVR-AM-00314', 'Genset', 'Eicher Motors Limited', '198 ES', 'HS Diesel'),
  ('RVR-AM-00315', 'Genset', 'Greaves Cotton Limited', 'GPA II-2.5', 'HS Diesel'),
  ('RVR-AM-00316', 'Genset', 'Kirloskar Oil Engines Limited', 'Chota Chilli 2.4', 'Petrol'),
  ('RVR-AM-00317', 'Genset', 'Mahindra and Mahindra Limited', '5 kVA Genset', 'HS Diesel'),
  ('RVR-AM-00318', 'Genset', 'Mahindra and Mahindra Limited', '2185', 'HS Diesel'),
  ('RVR-AM-00319', 'Genset', 'Cummins India Limited', 'C10D5P X1.3', 'HS Diesel'),
  ('RVR-AM-00320', 'Genset', 'Cummins India Limited', 'PX12000', 'HS Diesel'),
  ('RVR-AM-00321', 'Genset', 'HONDA INDIA POWER', 'GX390', 'HS Diesel'),
  ('RVR-AM-00322', 'Genset', 'Cummins India Limited', 'SP-IV-58.5', 'HS Diesel'),
  ('RVR-AM-00323', 'Genset', 'Mahindra and Mahindra Limited', 'M3205G5', 'HS Diesel'),
  ('RVR-AM-00324', 'Genset', 'Mahindra and Mahindra Limited', 'M4275G1', 'HS Diesel'),
  ('RVR-AM-00325', 'Genset', 'Mahindra and Mahindra Limited', 'H4485G2', 'HS Diesel'),
  ('RVR-AM-00326', 'Genset', 'Mahindra and Mahindra Limited', 'H6725G4', 'HS Diesel'),
  ('RVR-AM-00327', 'Genset', 'Mahindra and Mahindra Limited', 'RP 4057 C4', 'HS Diesel'),
  ('RVR-AM-00328', 'Genset', 'Mahindra and Mahindra Limited', 'M30DR', 'HS Diesel'),
  ('RVR-AM-00329', 'Genset', 'Mahindra and Mahindra Limited', 'RP 250310 C4', 'HS Diesel'),
  ('RVR-AM-00330', 'Genset', 'Mahindra and Mahindra Limited', 'RP 6382 C4', 'HS Diesel'),
  ('RVR-AM-00331', 'Genset', 'Eicher Motors Limited', 'JPS/30R', 'HS Diesel'),
  ('RVR-AM-00332', 'Genset', 'Caterpillar India Private Limited', 'DE 630', 'HS Diesel'),
  ('RVR-AM-00333', 'Genset', 'Kirloskar Oil Engines Limited', 'KG4-P-5.5AS', 'HS Diesel'),
  ('RVR-AM-00334', 'Genset', 'Cummins India Limited', 'C625D5P', 'HS Diesel'),
  ('RVR-AM-00335', 'Genset', 'Eicher Motors Limited', 'JPS/125R', 'HS Diesel'),
  ('RVR-AM-00336', 'GROOVE CUTTING MACHINE', 'V.S.T Tillers Tractors', 'VST 130 DI', 'HS Diesel'),
  ('RVR-AM-00337', 'Hydraulic Crawler Drill Rig', 'Epiroc India', 'AirROC D45', 'HS Diesel'),
  ('RVR-AM-00338', 'Hydraulic Jack', 'Orione Hydropower', '50 MT', NULL),
  ('RVR-AM-00339', 'Hydraulic Jack', 'Orione Hydropower', '25 MT', NULL),
  ('RVR-AM-00340', 'Hydraulic Mulcher Attachment', 'OMEF-GROUP', 'TE15-130DF', NULL),
  ('RVR-AM-00341', 'Integrated Concrete Boom Placer - ''KM & Hr''', 'Putzmeister Concrete Machines', 'BSF 36.09 H', 'HS Diesel'),
  ('RVR-AM-00342', 'Integrated Concrete Boom Placer - ''KM & Hr''', 'Putzmeister Concrete Machines', 'BSF 36.10 H', 'HS Diesel'),
  ('RVR-AM-00343', 'Integrated Concrete Boom Placer - ''KM & Hr''', 'Sany Heavy Industry', 'SYG5260THB-37', 'HS Diesel'),
  ('RVR-AM-00344', 'Integrated Concrete Boom Placer - ''KM & Hr''', 'Putzmeister Concrete Machines', 'BSF 42.10 H', 'HS Diesel'),
  ('RVR-AM-00345', 'Integrated Concrete Boom Placer - ''KM & Hr''', 'Putzmeister Concrete Machines', 'BSF 32.09', 'HS Diesel'),
  ('RVR-AM-00346', 'Integrated Concrete Boom Placer - ''KM & Hr''', 'Schwing Stetter India', 'S 36X', 'HS Diesel'),
  ('RVR-AM-00347', 'Integrated Concrete Boom Placer - ''KM & Hr''', 'Putzmeister Concrete Machines', 'M 46-5', 'HS Diesel'),
  ('RVR-AM-00348', 'Integrated Concrete Boom Placer - ''KM & Hr''', 'Sany Heavy Industry', 'SYG5423 THB 560C-8D', 'HS Diesel'),
  ('RVR-AM-00349', 'Integrated Concrete Boom Placer - ''KM & Hr''', 'Putzmeister Concrete Machines', 'BSF 42-5.10H', 'HS Diesel'),
  ('RVR-AM-00350', 'Integrated Concrete Boom Placer - ''KM & Hr''', 'Sany Heavy Industry', 'SYM5552THB 710SA', 'HS Diesel'),
  ('RVR-AM-00351', 'Integrated Road Sweeping Machine', 'TPS Infrastructure', 'TPS-VACSWEEP-750', 'HS Diesel'),
  ('RVR-AM-00352', 'Integrated Road Sweeping Machine', 'TPS Infrastructure', 'RSM-3', 'HS Diesel'),
  ('RVR-AM-00353', 'Integrated Transit Mixer - ''KM & Hr''', 'Schwing Stetter India', 'AM 7 SHC2', 'HS Diesel'),
  ('RVR-AM-00354', 'Integrated Transit Mixer - ''KM & Hr''', 'Greaves Infra', 'TM - 65XL', 'HS Diesel'),
  ('RVR-AM-00355', 'Integrated Transit Mixer - ''KM & Hr''', 'Schwing Stetter India', 'AM 6 SHD2', 'HS Diesel'),
  ('RVR-AM-00356', 'Integrated Transit Mixer - ''KM & Hr''', 'Greaves Infra', 'TM - 65', 'HS Diesel'),
  ('RVR-AM-00357', 'Integrated Transit Mixer - ''KM & Hr''', 'Liebherr India Private Limited', 'HTM 605', 'HS Diesel'),
  ('RVR-AM-00358', 'Integrated Transit Mixer - ''KM & Hr''', 'Ashok Leyland', '2820 RMC', 'HS Diesel'),
  ('RVR-AM-00359', 'Integrated Transit Mixer - ''KM & Hr''', 'Schwing Stetter India', 'AM 7 SHN2', 'HS Diesel'),
  ('RVR-AM-00360', 'Integrated Transit Mixer - ''KM & Hr''', 'Schwing Stetter India', 'AM7 SHN2', 'HS Diesel'),
  ('RVR-AM-00361', 'Integrated Transit Mixer - ''KM & Hr''', 'Schwing Stetter India', 'AM9 FHC2', 'HS Diesel'),
  ('RVR-AM-00362', 'Integrated Transit Mixer - ''KM & Hr''', 'Tata Motors Limited', 'Signa 2825K', 'HS Diesel'),
  ('RVR-AM-00363', 'Integrated Transit Mixer - ''KM & Hr''', 'Tata Motors Limited', 'Signa 2823.K', 'HS Diesel'),
  ('RVR-AM-00364', 'Integrated Transit Mixer - ''KM & Hr''', 'Schwing Stetter India', 'AM9 FHN2 RH', 'HS Diesel'),
  ('RVR-AM-00365', 'Jaw Crusher - Stationary', 'Puzzolana Machinery Fabricators', '36 x 24', NULL),
  ('RVR-AM-00366', 'Jaw Crusher - Stationary', 'Metso India', 'C106', NULL),
  ('RVR-AM-00367', 'Jaw Crusher - Stationary', 'Metso India', 'C-120', NULL),
  ('RVR-AM-00368', 'Jaw Crusher - Stationary', 'Metso India', 'JAW-UJ800', NULL),
  ('RVR-AM-00369', 'Jaw Crusher - Stationary', 'Puzzolana Machinery Fabricators', '44 X 32', NULL),
  ('RVR-AM-00370', 'Jaw Crusher - Stationary', 'Metso India', 'Nordberg C105', NULL),
  ('RVR-AM-00371', 'Jaw Crusher - Stationary', 'MachineTech Engineering', 'Ultra JAW UJ11080', NULL),
  ('RVR-AM-00372', 'Jaw Crusher - Wheel Mounted', 'Metso India', 'NW106', NULL),
  ('RVR-AM-00373', 'Jib Crane', 'Active Engg Services', '500', NULL),
  ('RVR-AM-00374', 'Jib Crane', 'Active Engg Services', 'AE1000VA', NULL),
  ('RVR-AM-00375', 'Kerb Cutting Machine', 'Himakshi Road-Cons Equipments', '32', 'HS Diesel'),
  ('RVR-AM-00376', 'Kerb Cutting Machine', 'Siddhivinayak Engineering Company', 'SKCM 610', NULL),
  ('RVR-AM-00377', 'Kerb Paver - Tyre Mounted', 'Apollo Equipments', 'KLM 40', 'Petrol'),
  ('RVR-AM-00378', 'Kerb Paver - Tyre Mounted', 'Apollo Equipments', 'KP 40', 'Petrol'),
  ('RVR-AM-00379', 'Kerb Paver - Tyre Mounted', 'Macons Equipments', 'MKM 351', 'HS Diesel'),
  ('RVR-AM-00380', 'Kerb Paver - with Track', 'Apollo Equipments', 'KLM-1200', 'HS Diesel'),
  ('RVR-AM-00381', 'Kerb Paver - with Track', 'AMMANN', 'KLM1200', 'HS Diesel'),
  ('RVR-AM-00382', 'Launching Girder', 'Bridgecon India', 'LG', NULL),
  ('RVR-AM-00383', 'Liner Making Machine', 'Taiyuan Huaye Heavy Industry', 'LH1500-1200-10', NULL),
  ('RVR-AM-00384', 'Magnetic Drill Machine', 'Makita Power Tools', 'HB350-2INA', NULL),
  ('RVR-AM-00385', 'Milling Machine - Track Mounted', 'Wirtgen India', 'W 130 CF', 'HS Diesel'),
  ('RVR-AM-00386', 'Mist Sprayer', 'ALL ADVANCE TECHNOLOGY MACHINES', 'AATM 30L', NULL),
  ('RVR-AM-00387', 'Mist Sprayer', 'Lokpal Industries', 'FS-20', NULL),
  ('RVR-AM-00388', 'Mobile Concrete Placer', 'Surelia Engineers', 'EMCP-56', 'HS Diesel'),
  ('RVR-AM-00389', 'Mobile Lighting Tower', 'ASKA', 'VT8', 'HS Diesel'),
  ('RVR-AM-00390', 'Mobile Lighting Tower', 'Atlas Copco India Limited', 'HiLight V5+', 'HS Diesel'),
  ('RVR-AM-00391', 'Mobile Lighting Tower', 'Ajashy Engineering', '5 HP Hybrid', 'HS Diesel'),
  ('RVR-AM-00392', 'Mobile Lighting Tower', 'Sigma Search Lights', '5AS3', 'HS Diesel'),
  ('RVR-AM-00393', 'Mobile Lighting Tower', 'Ajashy Engineering', '198ES', 'HS Diesel'),
  ('RVR-AM-00394', 'Mobile Lighting Tower', 'Doosan Bobcat', 'PL40', 'HS Diesel'),
  ('RVR-AM-00395', 'Mobile Lighting Tower', 'Eicher Motors Limited', 'JPS/105R', 'HS Diesel'),
  ('RVR-AM-00396', 'Mobile Service Van', 'Ajashy Engineering', 'SV09', 'HS Diesel'),
  ('RVR-AM-00397', 'Mobile Service Van', 'Ajashy Engineering', 'SV07 HM', 'HS Diesel'),
  ('RVR-AM-00398', 'Mobile Tower Crane - With Prime Mover', 'Action Construction Equipment', 'MTC - 2418', 'HS Diesel'),
  ('RVR-AM-00399', 'Mobile Tower Crane - With Prime Mover', 'Alpha Services', 'SP453', 'HS Diesel'),
  ('RVR-AM-00400', 'Mobile Tower Crane - Without Prime Mover', 'Action Construction Equipment', 'MTC - 2418 T', NULL),
  ('RVR-AM-00401', 'Mobile Tower Crane - Without Prime Mover', 'Action Construction Equipment', 'MTC - 3625', NULL),
  ('RVR-AM-00402', 'Modular Jack Up Barge', 'Local Manufacturer', '18x18x2.5 Mtr 150 MT Payload', 'HS Diesel'),
  ('RVR-AM-00403', 'Monkey Hoist', 'Acme Concrete Mixers', 'ACME - ML500', NULL),
  ('RVR-AM-00404', 'Monkey Hoist', 'Skipper Construction Equipment', 'SML 750', NULL),
  ('RVR-AM-00405', 'Monkey Hoist with Hourmeter', 'Innomac Engineering', 'ICL-500', NULL),
  ('RVR-AM-00406', 'Motocycle', 'Bajaj Auto', 'Motorcycle', 'Petrol'),
  ('RVR-AM-00407', 'Motocycle', 'Honda Motorcycle', 'Motorcycle', 'Petrol'),
  ('RVR-AM-00408', 'Motocycle', 'Hero Motocorp', 'Motorcycle', 'Petrol'),
  ('RVR-AM-00409', 'Motocycle', 'TVS Motor', 'Sport U-559', 'Petrol'),
  ('RVR-AM-00410', 'Motor Grader', 'Liugong India', 'CLG 414', 'HS Diesel'),
  ('RVR-AM-00411', 'Motor Grader', 'Caterpillar India Private Limited', '120 K2', 'HS Diesel'),
  ('RVR-AM-00412', 'Motor Grader', 'Caterpillar India Private Limited', '120 H', 'HS Diesel'),
  ('RVR-AM-00413', 'Motor Grader', 'Komatsu India Private Limited', 'GD511A', 'HS Diesel'),
  ('RVR-AM-00414', 'Motor Grader', 'Caterpillar India Private Limited', '120K', 'HS Diesel'),
  ('RVR-AM-00415', 'Motor Grader', 'Action Construction Equipment', 'AG-176', 'HS Diesel'),
  ('RVR-AM-00416', 'Motor Grader', 'Komatsu India Private Limited', 'GD535', 'HS Diesel'),
  ('RVR-AM-00417', 'Motor Grader', 'XCMG', 'G1605', 'HS Diesel'),
  ('RVR-AM-00418', 'Motor Grader', 'BEML', 'BG 605', 'HS Diesel'),
  ('RVR-AM-00419', 'Motor Grader', 'Komatsu India Private Limited', 'GD555', 'HS Diesel'),
  ('RVR-AM-00420', 'Motor Grader', 'SEM Machinery Co.', 'SEM 915', 'HS Diesel'),
  ('RVR-AM-00421', 'Motor Grader', 'Schwing Stetter India', 'GR1705', 'HS Diesel'),
  ('RVR-AM-00422', 'Multi Utility Vehicle', 'Toyota Kirloskar Motor', 'Innova', 'HS Diesel'),
  ('RVR-AM-00423', 'Multi Utility Vehicle', 'Maruti Suzuki', 'Ertiga', 'HS Diesel'),
  ('RVR-AM-00424', 'Multi Utility Vehicle', 'Mahindra and Mahindra Limited', 'Scorpio', 'HS Diesel'),
  ('RVR-AM-00425', 'Multi Utility Vehicle', 'Mahindra and Mahindra Limited', 'TUV 300', 'HS Diesel'),
  ('RVR-AM-00426', 'Multi Utility Vehicle', 'Maruti Suzuki', 'EECO', 'Petrol'),
  ('RVR-AM-00427', 'Multi Utility Vehicle', 'Mahindra and Mahindra Limited', 'Marazzo', 'HS Diesel'),
  ('RVR-AM-00428', 'Multi Utility Vehicle', 'Force Motors', 'Ambulance', 'HS Diesel'),
  ('RVR-AM-00429', 'Multi Utility Vehicle', 'Maruti Suzuki', 'Omni BS-IV', 'Petrol'),
  ('RVR-AM-00430', 'Multi Utility Vehicle', 'Tata Motors Limited', 'Sumo', 'HS Diesel'),
  ('RVR-AM-00431', 'Multi Utility Vehicle', 'Toyota Kirloskar Motor', 'Fortuner', 'HS Diesel'),
  ('RVR-AM-00432', 'Multi Utility Vehicle', 'Mahindra and Mahindra Limited', 'Supro ZX', 'HS Diesel'),
  ('RVR-AM-00433', 'Multi Utility Vehicle', 'Toyota Kirloskar Motor', 'Glanza V', 'Petrol'),
  ('RVR-AM-00434', 'Multi Utility Vehicle', 'Force Motors', 'T1 AMB 3350 FM2.6 BSVI', 'HS Diesel'),
  ('RVR-AM-00435', 'Multi Utility Vehicle', 'Force Motors', 'Trax Toofan', 'HS Diesel'),
  ('RVR-AM-00436', 'Non Measurable Miscellaneous', 'Miscellaneous', 'Miscellaneous', NULL),
  ('RVR-AM-00437', 'Over Pumping Unit - Engine Driven', 'Akhand', 'Standard', 'HS Diesel'),
  ('RVR-AM-00438', 'Over Pumping Unit - Engine Driven', 'BALUJA INDUSTRIES', 'Standard', 'HS Diesel'),
  ('RVR-AM-00439', 'Passenger and Material Hoist', 'Spartan Engineering', 'SPM 250V', NULL),
  ('RVR-AM-00440', 'Passenger and Material Hoist', 'Alikraft Engineers Private Limited', 'AK1000', NULL),
  ('RVR-AM-00441', 'Passenger and Material Hoist', 'Spartan Engineering', 'SPM 150V', NULL),
  ('RVR-AM-00442', 'Passenger and Material Hoist', 'Spartan Engineering', 'SPM 100V', NULL),
  ('RVR-AM-00443', 'Passenger and Material Hoist', 'Spartan Engineering', 'SMH 150P', NULL),
  ('RVR-AM-00444', 'Passenger and Material Hoist', 'Alimak Group', 'ALIMAK SC 45/26', NULL),
  ('RVR-AM-00445', 'Passenger and Material Hoist', 'KYB Conmat', 'RPCE10', NULL),
  ('RVR-AM-00446', 'Passenger and Material Hoist', 'CMAC India', 'SC-200', NULL),
  ('RVR-AM-00447', 'Passenger and Material Hoist', 'Innomac Engineering', 'IPM 200', NULL),
  ('RVR-AM-00448', 'Passenger and Material Hoist', 'Innomac Engineering', 'ICH-150', NULL),
  ('RVR-AM-00449', 'Passenger and Material Hoist', 'CMAC India', 'SC 200', NULL),
  ('RVR-AM-00450', 'Pick and Carry Crane', 'Escorts Construction Equipment', 'F-15', 'HS Diesel'),
  ('RVR-AM-00451', 'Pick and Carry Crane', 'Escorts Construction Equipment', 'Hydra 14', 'HS Diesel'),
  ('RVR-AM-00452', 'Pick and Carry Crane', 'Action Construction Equipment', '12XW', 'HS Diesel'),
  ('RVR-AM-00453', 'Pick and Carry Crane', 'Action Construction Equipment', '14XW', 'HS Diesel'),
  ('RVR-AM-00454', 'Pick and Carry Crane', 'Escorts Construction Equipment', 'Hydra 12', 'HS Diesel'),
  ('RVR-AM-00455', 'Pick and Carry Crane', 'Escorts Construction Equipment', 'TRX 2319', 'HS Diesel'),
  ('RVR-AM-00456', 'Pick and Carry Crane', 'Escorts Construction Equipment', 'F-20', 'HS Diesel'),
  ('RVR-AM-00457', 'Pick and Carry Crane', 'Action Construction Equipment', 'FX 230', 'HS Diesel'),
  ('RVR-AM-00458', 'Pick and Carry Crane', 'Action Construction Equipment', 'F-210', 'HS Diesel'),
  ('RVR-AM-00459', 'Pick and Carry Crane', 'Escorts Construction Equipment', 'Hydra 10', 'HS Diesel'),
  ('RVR-AM-00460', 'Pick and Carry Crane', 'Action Construction Equipment', 'NXP 150', 'HS Diesel'),
  ('RVR-AM-00461', 'Pick and Carry Crane', 'Action Construction Equipment', 'F150', 'HS Diesel'),
  ('RVR-AM-00462', 'Pick and Carry Crane', 'Action Construction Equipment', 'FX 150', 'HS Diesel'),
  ('RVR-AM-00463', 'Pick and Carry Crane', 'Action Construction Equipment', 'FX 210', 'HS Diesel'),
  ('RVR-AM-00464', 'Pick and Carry Crane', 'Escorts Construction Equipment', 'TRX - 15', 'HS Diesel'),
  ('RVR-AM-00465', 'Pick and Carry Crane', 'Action Construction Equipment', '15XW', 'HS Diesel'),
  ('RVR-AM-00466', 'Pick and Carry Crane', 'Action Construction Equipment', '18XW', 'HS Diesel'),
  ('RVR-AM-00467', 'Pick and Carry Crane', 'Action Construction Equipment', 'F250', 'HS Diesel'),
  ('RVR-AM-00468', 'Pick and Carry Crane', 'Escorts Construction Equipment', 'F-23', 'HS Diesel'),
  ('RVR-AM-00469', 'Pick and Carry Crane', 'Indo Farm Equipment', 'Indo Power 14 FNX', 'HS Diesel'),
  ('RVR-AM-00470', 'Pile Cage Fabrication Machine', 'Everest Engineering Equipment', 'YFM1500', NULL),
  ('RVR-AM-00471', 'Piling Rig', 'MAIT India', 'HR 180', 'HS Diesel'),
  ('RVR-AM-00472', 'Piling Rig', 'MAIT India', 'HR 260', 'HS Diesel'),
  ('RVR-AM-00473', 'Piling Rig', 'Sany Heavy Industry', 'SR285R C10', 'HS Diesel'),
  ('RVR-AM-00474', 'Piling Rig', 'Sany Heavy Industry', 'SR235', 'HS Diesel'),
  ('RVR-AM-00475', 'Piling Rig', 'Zoomlion India', 'ZR 185A', 'HS Diesel'),
  ('RVR-AM-00476', 'Piling Rig', 'Sany Heavy Industry', 'SR215', 'HS Diesel'),
  ('RVR-AM-00477', 'Piling Rig', 'Casagrande', 'B200XP', 'HS Diesel'),
  ('RVR-AM-00478', 'Piling Rig', 'XCMG', 'XR240I', 'HS Diesel'),
  ('RVR-AM-00479', 'Pipe Straightening Machine', 'Jagjit Industries', '5 HP', NULL),
  ('RVR-AM-00480', 'Pipe Threading Machine', 'Nandini Entrepreneur', 'NE-T4-100', NULL),
  ('RVR-AM-00481', 'Plastering Pump - Motor Driven', 'Putzmeister Concrete Machines', 'MP 25', NULL),
  ('RVR-AM-00482', 'Plate Compactor - Engine Driven', 'Wacker Neuson', 'DPU3070H', 'HS Diesel'),
  ('RVR-AM-00483', 'Plate Compactor - Engine Driven', 'Greaves Cotton Limited', 'GFP - 5000', 'HS Diesel'),
  ('RVR-AM-00484', 'Plate Compactor - Engine Driven', 'Jaypee India Limited', 'VC 25', 'HS Diesel'),
  ('RVR-AM-00485', 'Plate Compactor - Engine Driven', 'Wacker Neuson', 'DPU4545H', 'HS Diesel'),
  ('RVR-AM-00486', 'Plate Compactor - Engine Driven', 'Husqvarna Construction', 'LF 160 D', 'HS Diesel'),
  ('RVR-AM-00487', 'Pneumatic Crawler Drill Rig', 'Atlas Copco India Limited', 'ROC 203', NULL),
  ('RVR-AM-00488', 'Pneumatic Crawler Drill Rig', 'Atlas Copco India Limited', 'AirROC D35 (LM 100)', NULL),
  ('RVR-AM-00489', 'Pneumatic Tyre Roller', 'Dynapac', 'CP142', 'HS Diesel'),
  ('RVR-AM-00490', 'Pneumatic Tyre Roller', 'Volvo India Private Limited', 'PTR220', 'HS Diesel'),
  ('RVR-AM-00491', 'Pneumatic Tyre Roller', 'Dynapac', 'CP271', 'HS Diesel'),
  ('RVR-AM-00492', 'Pothole Repairing Machine', 'AEW Group', 'PRM-15', 'HS Diesel'),
  ('RVR-AM-00493', 'Power Tiller', 'V.S.T Tillers Tractors', 'Shakti 130 DI', 'HS Diesel'),
  ('RVR-AM-00494', 'Rebar Coupler Threading Machine', 'Rohita', 'Rohita 1.5', NULL),
  ('RVR-AM-00495', 'Recovery Crane Truck', 'Tata Motors Limited', 'LPT 1613', 'HS Diesel'),
  ('RVR-AM-00496', 'Road Sweeper Tractor Attachment', 'Vibrant Construction Equipment', '5405', NULL),
  ('RVR-AM-00497', 'Road Sweeper Tractor Attachment', 'Apollo Equipments', 'Broom', NULL),
  ('RVR-AM-00498', 'Road Sweeper Tractor Attachment', 'Vibrant Construction Equipment', 'Hydraulic Broomer', NULL),
  ('RVR-AM-00499', 'Road Sweeper Tractor Attachment', 'Vibrant Construction Equipment', 'VBR 2200', NULL),
  ('RVR-AM-00500', 'Rock Breaker', 'Volvo India Private Limited', 'HB22', NULL),
  ('RVR-AM-00501', 'Rock Breaker', 'Hyundai CE', 'HDB-230', NULL),
  ('RVR-AM-00502', 'Rock Breaker', 'JCB India Limited', 'HM 2160HD', NULL),
  ('RVR-AM-00503', 'Rock Breaker', 'Dozco', 'D135', NULL),
  ('RVR-AM-00504', 'Rock Breaker', 'OKADA AIYON', '2800J', NULL),
  ('RVR-AM-00505', 'Rope Suspended Platform', 'Spartan Engineering', 'SPR 1000', NULL),
  ('RVR-AM-00506', 'Rope Suspended Platform', 'CMAC India', 'CMAC 800', NULL),
  ('RVR-AM-00507', 'Rope Suspended Platform', 'Jaypee India Limited', 'JSP 1000', NULL),
  ('RVR-AM-00508', 'Rope Suspended Platform', 'CMAC India', 'ZLP1000', NULL),
  ('RVR-AM-00509', 'Rope Suspended Platform', 'Innomac Engineering', 'ISP1000', NULL),
  ('RVR-AM-00510', 'Rope Suspended Platform', 'Spartan Engineering', 'ZLP 800', NULL),
  ('RVR-AM-00511', 'Rope Suspended Platform', 'CMAC India', 'SRP-1000', NULL),
  ('RVR-AM-00512', 'Rough Terrain Crane - Hours Based', 'Grove Crane', 'RT 740', 'HS Diesel'),
  ('RVR-AM-00513', 'Rough Terrain Crane - HR & KM based', 'Grove Crane', 'RT 740B', 'HS Diesel'),
  ('RVR-AM-00514', 'Sand Washing Plant', 'CDE Asia Limited', 'CDE COMBO X70', NULL),
  ('RVR-AM-00515', 'Sand Washing Plant', 'Cflo Combo', 'X70', NULL),
  ('RVR-AM-00516', 'Scissor Lift - Battery Driven', 'JCB India Limited', 'S4550E', NULL),
  ('RVR-AM-00517', 'Scissor Lift - Battery Driven', 'XCMG', 'XG1212HD', NULL),
  ('RVR-AM-00518', 'Scissor Lift - Battery Driven', 'JCB India Limited', 'S2646E', NULL),
  ('RVR-AM-00519', 'Screw Compressor - Engine Driven', 'Atlas Copco India Limited', 'XAT266', 'HS Diesel'),
  ('RVR-AM-00520', 'Screw Compressor - Engine Driven', 'Atlas Copco India Limited', 'XA280', 'HS Diesel'),
  ('RVR-AM-00521', 'Screw Compressor - Engine Driven', 'Atlas Copco India Limited', 'XAH210', 'HS Diesel'),
  ('RVR-AM-00522', 'Screw Compressor - Engine Driven', 'Atlas Copco India Limited', 'XA 76', 'HS Diesel'),
  ('RVR-AM-00523', 'Screw Compressor - Engine Driven', 'Ingersoll Rand India Limited', 'P310', 'HS Diesel'),
  ('RVR-AM-00524', 'Screw Compressor - Engine Driven', 'Elgi Equipments Limited', 'DT300-100', 'HS Diesel'),
  ('RVR-AM-00525', 'Screw Compressor - Engine Driven', 'Atlas Copco India Limited', 'XAS 450-200', 'HS Diesel'),
  ('RVR-AM-00526', 'Screw Compressor - Engine Driven', 'Elgi Equipments Limited', 'PG450-150', 'HS Diesel'),
  ('RVR-AM-00527', 'Screw Compressor - Engine Driven', 'Atlas Copco India Limited', 'XA146HD', 'HS Diesel'),
  ('RVR-AM-00528', 'Screw Compressor - Engine Driven', 'Atlas Copco India Limited', 'XAXS 600', 'HS Diesel'),
  ('RVR-AM-00529', 'Screw Compressor - Engine Driven', 'Elgi Equipments Limited', 'PG300-100', 'HS Diesel'),
  ('RVR-AM-00530', 'Screw Compressor - Engine Driven', 'Elgi Equipments Limited', 'DS600-200', 'HS Diesel'),
  ('RVR-AM-00531', 'Screw Compressor - Engine Driven', 'Elgi Equipments Limited', 'PG330-100', 'HS Diesel'),
  ('RVR-AM-00532', 'Screw Compressor - Motor Driven', 'Atlas Copco India Limited', 'XAT 400E', NULL),
  ('RVR-AM-00533', 'Screw Compressor - Motor Driven', 'Anest Iwata Motherson', 'TLS201010S1', NULL),
  ('RVR-AM-00534', 'Screw Compressor - Motor Driven', 'Chicago Pneumatic', 'CPC60', NULL),
  ('RVR-AM-00535', 'Screw Compressor - Motor Driven', 'Elgi Equipments Limited', 'TS15 HN', NULL),
  ('RVR-AM-00536', 'Screw Compressor - Motor Driven', 'Elgi Equipments Limited', 'SS03LB-10', NULL),
  ('RVR-AM-00537', 'Screw Compressor - Motor Driven', 'Elgi Equipments Limited', 'TS10 LB', NULL),
  ('RVR-AM-00538', 'Screw Compressor - Motor Driven', 'Elgi Equipments Limited', 'TS10 LB12', NULL),
  ('RVR-AM-00539', 'Screw Compressor - Motor Driven', 'NMF Equipments', 'NGR122', NULL),
  ('RVR-AM-00540', 'Screw Compressor - Motor Driven', 'Sadguru Enterprise', '10 TS', NULL),
  ('RVR-AM-00541', 'Screw Compressor - Motor Driven', 'Elgi Equipments Limited', 'EG37', NULL),
  ('RVR-AM-00542', 'Screw Compressor - Motor Driven', 'Elgi Equipments Limited', 'SS02LB10', NULL),
  ('RVR-AM-00543', 'Screw Compressor - Motor Driven', 'Atlas Copco India Limited', 'XA140E', NULL),
  ('RVR-AM-00544', 'Screw Compressor - Motor Driven', 'Anest Iwata Motherson', 'TS30L', NULL),
  ('RVR-AM-00545', 'Screw Compressor - Motor Driven', 'Atlas Copco India Limited', 'XA500E', NULL),
  ('RVR-AM-00546', 'Self Loading Concrete Mixer', 'Ajax Fiori', 'Agro 4000', 'HS Diesel'),
  ('RVR-AM-00547', 'Self Loading Concrete Mixer', 'Schwing Stetter India', 'SLM 2100', 'HS Diesel'),
  ('RVR-AM-00548', 'Self Propelled Repairing Unit', 'Uralets', 'PC 1300', 'HS Diesel'),
  ('RVR-AM-00549', 'SEWAGE TREATMENT PLANT', 'Chempure Technologies', '100 KLD', NULL),
  ('RVR-AM-00550', 'Shotcrete Machine', 'CIFA India', 'CSS-3', 'HS Diesel'),
  ('RVR-AM-00551', 'Shotcrete Machine', 'Schwing Stetter India', 'TSR 30.14 Mark IIs', 'HS Diesel'),
  ('RVR-AM-00552', 'Shotcrete Machine', 'Sany Heavy Industry', 'SPJ 3217K', 'HS Diesel'),
  ('RVR-AM-00553', 'Silo', 'Machine Tool Aids', 'Silos', NULL),
  ('RVR-AM-00554', 'Silo', 'Schwing Stetter India', 'Silo', NULL),
  ('RVR-AM-00555', 'Silo', 'Schwing Stetter India', 'MICRO SILICA', NULL),
  ('RVR-AM-00556', 'Silo', 'Others', 'Micro Silica', NULL),
  ('RVR-AM-00557', 'Skid Steer Loader', 'JCB India Limited', 'SSL 155', 'HS Diesel'),
  ('RVR-AM-00558', 'Skid Steer Loader', 'Doosan Bobcat', 'S450', 'HS Diesel'),
  ('RVR-AM-00559', 'Skid Steer Loader', 'Doosan Bobcat', 'S450 T2', 'HS Diesel'),
  ('RVR-AM-00560', 'Slip-form Paver', 'Wirtgen India', 'SP25', 'HS Diesel'),
  ('RVR-AM-00561', 'Slip-form Paver', 'Wirtgen India', 'SP 94 / SP 94i', 'HS Diesel'),
  ('RVR-AM-00562', 'Slip-form Paver', 'Wirtgen India', 'SP 1600', 'HS Diesel'),
  ('RVR-AM-00563', 'Solar Mobile Lighting Tower', 'UV POWER', 'Uv Diksuchi 003', NULL),
  ('RVR-AM-00564', 'Solar Mobile Lighting Tower', 'UV POWER', 'UV Diksuchi 002', NULL),
  ('RVR-AM-00565', 'Stationary Placing Boom', 'Putzmeister Concrete Machines', 'MX32-4', NULL),
  ('RVR-AM-00566', 'Stationary Placing Boom', 'Putzmeister Concrete Machines', 'MX 35-4Z', NULL),
  ('RVR-AM-00567', 'Stationary Placing Boom', 'Putzmeister Concrete Machines', 'MXR 35-4Z', NULL),
  ('RVR-AM-00568', 'Stirrup Bending Machine', 'Acme Concrete Mixers', 'AGF-20', NULL),
  ('RVR-AM-00569', 'STRETCH WRAPPING MACHINE', 'Penguin Engineers', 'CLASSIC', NULL),
  ('RVR-AM-00570', 'Tandem Vibratory Compactor', 'Case New Holland CE', '450 DX', 'HS Diesel'),
  ('RVR-AM-00571', 'Tandem Vibratory Compactor', 'Ingersoll Rand India Limited', 'DD90', 'HS Diesel'),
  ('RVR-AM-00572', 'Tandem Vibratory Compactor', 'Wirtgen India', 'HAMM HD99', 'HS Diesel'),
  ('RVR-AM-00573', 'Tandem Vibratory Compactor', 'Dynapac', 'CC 125', 'HS Diesel'),
  ('RVR-AM-00574', 'Tandem Vibratory Compactor', 'Greaves Infra', 'BW 151 AD-2', 'HS Diesel'),
  ('RVR-AM-00575', 'Tandem Vibratory Compactor', 'Atlas Copco India Limited', 'CC 385 HF', 'HS Diesel'),
  ('RVR-AM-00576', 'Tandem Vibratory Compactor', 'Volvo India Private Limited', 'DD90', 'HS Diesel'),
  ('RVR-AM-00577', 'Tandem Vibratory Compactor', 'Atlas Copco India Limited', 'CC125', 'HS Diesel'),
  ('RVR-AM-00578', 'Tandem Vibratory Compactor', 'JCB India Limited', 'VMT 300 CEV 5', 'HS Diesel'),
  ('RVR-AM-00579', 'Tandem Vibratory Compactor', 'AMMANN', 'ARX 32.2', 'HS Diesel'),
  ('RVR-AM-00580', 'Telehandler', 'JCB India Limited', 'Loadall 530 - 110', 'HS Diesel'),
  ('RVR-AM-00581', 'Telescopic Boom Lift', 'Genie', 'S-85', 'HS Diesel'),
  ('RVR-AM-00582', 'Telescopic Clamshell Dipper', 'Kobelco CE', 'SK220 XD LC', 'HS Diesel'),
  ('RVR-AM-00583', 'Telescopic Crawler Cranes', 'Liebherr India Private Limited', 'LTR 1220', 'HS Diesel'),
  ('RVR-AM-00584', 'Texture Curing Machine', 'Wirtgen India', 'TCM 180', 'HS Diesel'),
  ('RVR-AM-00585', 'Tipper', 'Tata Motors Limited', 'LPK 2518', 'HS Diesel'),
  ('RVR-AM-00586', 'Tipper', 'Tata Motors Limited', 'LPK 2516', 'HS Diesel'),
  ('RVR-AM-00587', 'Tipper', 'Ashok Leyland', '2516', 'HS Diesel'),
  ('RVR-AM-00588', 'Tipper', 'Ashok Leyland', '2518', 'HS Diesel'),
  ('RVR-AM-00589', 'Tipper', 'Bharat Benz', '2523C', 'HS Diesel'),
  ('RVR-AM-00590', 'Tipper', 'Bharat Benz', '2528C', 'HS Diesel'),
  ('RVR-AM-00591', 'Tipper', 'Tata Motors Limited', 'Signa 2832.K', 'HS Diesel'),
  ('RVR-AM-00592', 'Tipper', 'Mahindra and Mahindra Limited', 'Blazo X 28', 'HS Diesel'),
  ('RVR-AM-00593', 'Tipper - HR & KM Based', 'Mahindra and Mahindra Limited', 'Blazo X 25', 'HS Diesel'),
  ('RVR-AM-00594', 'Tipper - HR & KM Based', 'Tata Motors Limited', 'LPK 2523', 'HS Diesel'),
  ('RVR-AM-00595', 'Tipper - HR & KM Based', 'Ashok Leyland', '2523', 'HS Diesel'),
  ('RVR-AM-00596', 'Tipper - HR & KM Based', 'Mahindra and Mahindra Limited', 'Blazo X 31', 'HS Diesel'),
  ('RVR-AM-00597', 'Tipper - HR & KM Based', 'Volvo India Private Limited', 'FMX 460', 'HS Diesel'),
  ('RVR-AM-00598', 'Tipper - HR & KM Based', 'AMW Motors Limited', '3118 IL', 'HS Diesel'),
  ('RVR-AM-00599', 'Tipper - HR & KM Based', 'Tata Motors Limited', 'Prima 2528K', 'HS Diesel'),
  ('RVR-AM-00600', 'Tipper - HR & KM Based', 'Eicher Motors Limited', 'Pro 6028T', 'HS Diesel'),
  ('RVR-AM-00601', 'Tipper - HR & KM Based', 'Bharat Benz', '2823C', 'HS Diesel'),
  ('RVR-AM-00602', 'Tipper - HR & KM Based', 'Tata Motors Limited', 'LPK 1618', 'HS Diesel'),
  ('RVR-AM-00603', 'Tipper - HR & KM Based', 'Tata Motors Limited', 'Prima LX 2830', 'HS Diesel'),
  ('RVR-AM-00604', 'Tipper - HR & KM Based', 'Mahindra and Mahindra Limited', 'Loadking', 'HS Diesel'),
  ('RVR-AM-00605', 'Tipper - HR & KM Based', 'Tata Motors Limited', 'Signa 2823K', 'HS Diesel'),
  ('RVR-AM-00606', 'Tipper - HR & KM Based', 'Bharat Benz', '2828C', 'HS Diesel'),
  ('RVR-AM-00607', 'Tipper - HR & KM Based', 'Ashok Leyland', '3525 TU', 'HS Diesel'),
  ('RVR-AM-00608', 'Tipper - HR & KM Based', 'Eicher Motors Limited', 'PRO 6025T', 'HS Diesel'),
  ('RVR-AM-00609', 'Tipper - HR & KM Based', 'Ashok Leyland', '2820 TU', 'HS Diesel'),
  ('RVR-AM-00610', 'Tipper - HR & KM Based', 'Tata Motors Limited', 'SIGNA 3525 TK', 'HS Diesel'),
  ('RVR-AM-00611', 'Tipper - HR & KM Based', 'Ashok Leyland', '2825T', 'HS Diesel'),
  ('RVR-AM-00612', 'Tipper - HR & KM Based', 'Tata Motors Limited', 'SIGNA 2830.K', 'HS Diesel'),
  ('RVR-AM-00613', 'Tipper - HR & KM Based', 'Tata Motors Limited', 'Prima LX 3130.K', 'HS Diesel'),
  ('RVR-AM-00614', 'Tipper - HR & KM Based', 'Tata Motors Limited', 'Prima 3530.K', 'HS Diesel'),
  ('RVR-AM-00615', 'Tipper - HR & KM Based', 'Ashok Leyland', 'NE 2832N', 'HS Diesel'),
  ('RVR-AM-00616', 'Tough Rider', 'Universal Construction', 'Rider 4X4', 'HS Diesel'),
  ('RVR-AM-00617', 'Tough Rider', 'Cosmos Construction Machinery', 'Tough Rider 4x4', 'HS Diesel'),
  ('RVR-AM-00618', 'Tough Rider', 'Universal Construction', 'JKTR2', 'HS Diesel'),
  ('RVR-AM-00619', 'Tower Crane', 'Zoomlion India', 'TC 5013B6', NULL),
  ('RVR-AM-00620', 'Tower Crane', 'Omega Construction', 'QTZ 630', NULL),
  ('RVR-AM-00621', 'Tower Crane', 'Potain Tower Crane', 'MCT 85 F5', NULL),
  ('RVR-AM-00622', 'Tower Crane', 'Action Construction Equipment', 'TC 5540', NULL),
  ('RVR-AM-00623', 'Tower Crane', 'Zoomlion India', 'TCT 7527', NULL),
  ('RVR-AM-00624', 'Tower Crane', 'Spartan Engineering', 'CTT80 F6', NULL),
  ('RVR-AM-00625', 'Tower Crane', 'Liebherr India Private Limited', 'TC100 LC', NULL),
  ('RVR-AM-00626', 'Tower Crane', 'SHIRKE-POTAIN', 'MC 85A', NULL),
  ('RVR-AM-00627', 'Tower Crane', 'Zoomlion India', 'WA7025-10E', NULL),
  ('RVR-AM-00628', 'Tower Crane', 'Zoomlion India', 'WA7527-16D', NULL),
  ('RVR-AM-00629', 'Tower Crane', 'Zoomlion India', 'WA6015-8A', NULL),
  ('RVR-AM-00630', 'Tower Crane', 'Zoomlion India', 'D800-42', NULL),
  ('RVR-AM-00631', 'Track Mounted Cone Crusher', 'Metso India', 'Lokotrack LT200HP', 'HS Diesel'),
  ('RVR-AM-00632', 'Track Mounted Jaw Crusher', 'Metso India', 'Lokotrack LT106', 'HS Diesel'),
  ('RVR-AM-00633', 'Track Mounted Screen Plant', 'Metso India', 'Lokotrack ST4.8', 'HS Diesel'),
  ('RVR-AM-00634', 'Track Mounted Screen Plant', 'Terex PowerScreen', 'Warrior 1200', 'HS Diesel'),
  ('RVR-AM-00635', 'Tractor', 'Mahindra and Mahindra Limited', '265 DI', 'HS Diesel'),
  ('RVR-AM-00636', 'Tractor', 'Mahindra and Mahindra Limited', '605 DI', 'HS Diesel'),
  ('RVR-AM-00637', 'Tractor', 'Mahindra and Mahindra Limited', '475 DI', 'HS Diesel'),
  ('RVR-AM-00638', 'Tractor', 'Mahindra and Mahindra Limited', '575 DI', 'HS Diesel'),
  ('RVR-AM-00639', 'Tractor', 'John Deere India Private Limited', '5310', 'HS Diesel'),
  ('RVR-AM-00640', 'Tractor', 'John Deere India Private Limited', '5075E', 'HS Diesel'),
  ('RVR-AM-00641', 'Tractor', 'Mahindra and Mahindra Limited', 'Swaraj 735', 'HS Diesel'),
  ('RVR-AM-00642', 'Tractor', 'New Holland Tractors', '5500', 'HS Diesel'),
  ('RVR-AM-00643', 'Tractor', 'Mahindra and Mahindra Limited', '585 DI', 'HS Diesel'),
  ('RVR-AM-00644', 'Tractor', 'Escorts Limited', 'Powertrac 445 Plus', 'HS Diesel'),
  ('RVR-AM-00645', 'Tractor', 'Punjab Tractor Limited', 'Swaraj 724', 'HS Diesel'),
  ('RVR-AM-00646', 'Tractor', 'Sonalika Tractors', 'DI 732', 'HS Diesel'),
  ('RVR-AM-00647', 'Tractor', 'TAFE Limited', 'Eicher 242', 'HS Diesel'),
  ('RVR-AM-00648', 'Tractor', 'Eicher Tractors', 'Eicher 380', 'HS Diesel'),
  ('RVR-AM-00649', 'Tractor', 'Punjab Tractor Limited', 'Swaraj 855 FE', 'HS Diesel'),
  ('RVR-AM-00650', 'Tractor', 'Sonalika Tractors', 'DI 60', 'HS Diesel'),
  ('RVR-AM-00651', 'Tractor', 'Mahindra and Mahindra Limited', 'Shaktimaan 30', 'HS Diesel'),
  ('RVR-AM-00652', 'Tractor', 'Sonalika Tractors', 'DI 745 III', 'HS Diesel'),
  ('RVR-AM-00653', 'Tractor', 'Farmtrac', '6060', 'HS Diesel'),
  ('RVR-AM-00654', 'Tractor', 'New Holland Tractors', '3630', 'HS Diesel'),
  ('RVR-AM-00655', 'Tractor', 'New Holland Tractors', '3510', 'HS Diesel'),
  ('RVR-AM-00656', 'Tractor', 'Massey Ferguson India', '241 DI', 'HS Diesel'),
  ('RVR-AM-00657', 'Tractor', 'Massey Ferguson India', '9500', 'HS Diesel'),
  ('RVR-AM-00658', 'Tractor', 'Mahindra and Mahindra Limited', '275 DI', 'HS Diesel'),
  ('RVR-AM-00659', 'Tractor', 'Mahindra and Mahindra Limited', '295 DI', 'HS Diesel'),
  ('RVR-AM-00660', 'Tractor', 'Escorts Limited', 'Farmtrac 65 EPI', 'HS Diesel'),
  ('RVR-AM-00661', 'Tractor', 'Escorts Limited', 'Powertrac 434', 'HS Diesel'),
  ('RVR-AM-00662', 'Tractor', 'Mahindra and Mahindra Limited', 'YUVO 415 DI', 'HS Diesel'),
  ('RVR-AM-00663', 'Tractor', 'John Deere India Private Limited', '5405', 'HS Diesel'),
  ('RVR-AM-00664', 'Tractor', 'New Holland Tractors', '3230 NX', 'HS Diesel'),
  ('RVR-AM-00665', 'Tractor', 'New Holland Tractors', '3600 A1', 'HS Diesel'),
  ('RVR-AM-00666', 'Tractor', 'New Holland Tractors', '3037', 'HS Diesel'),
  ('RVR-AM-00667', 'Tractor', 'Punjab Tractor Limited', 'Swaraj 742XT', 'HS Diesel'),
  ('RVR-AM-00668', 'Tractor', 'Punjab Tractor Limited', 'Swaraj 834XM', 'HS Diesel'),
  ('RVR-AM-00669', 'Tractor', 'Mahindra and Mahindra Limited', 'Swaraj 744 FE', 'HS Diesel'),
  ('RVR-AM-00670', 'Tractor', 'Sonalika Tractors', 'DI 740', 'HS Diesel'),
  ('RVR-AM-00671', 'Tractor', 'John Deere India Private Limited', '5036 D', 'HS Diesel'),
  ('RVR-AM-00672', 'Tractor', 'John Deere India Private Limited', '5039 D', 'HS Diesel'),
  ('RVR-AM-00673', 'Tractor', 'John Deere India Private Limited', '5042D', 'HS Diesel'),
  ('RVR-AM-00674', 'Tractor', 'Sonalika Tractors', 'DI 35', 'HS Diesel'),
  ('RVR-AM-00675', 'Tractor', 'Massey Ferguson', '1035 DI', 'HS Diesel'),
  ('RVR-AM-00676', 'Tractor', 'Eicher Tractors', 'EICHER 551', 'HS Diesel'),
  ('RVR-AM-00677', 'Tractor', 'Kubota Agricultural Machinery', 'MU4501', 'HS Diesel'),
  ('RVR-AM-00678', 'Tractor', 'Escorts Limited', 'Powertrac Euro 45', 'HS Diesel'),
  ('RVR-AM-00679', 'Tractor', 'Force Motors', 'SANMAN 6000 LT', 'HS Diesel'),
  ('RVR-AM-00680', 'Tractor', 'Captain Tractors', '280-PS-OB-LD', 'HS Diesel'),
  ('RVR-AM-00681', 'Tractor', 'Massey Ferguson', 'MF 8055', 'HS Diesel'),
  ('RVR-AM-00682', 'Tractor', 'Sonalika Tractors', 'DI-734', 'HS Diesel'),
  ('RVR-AM-00683', 'Tractor', 'Mahindra and Mahindra Limited', 'SWARAJ 834 FE', 'HS Diesel'),
  ('RVR-AM-00684', 'Tractor Truck', 'AMW Motors Limited', '4018 TR', 'HS Diesel'),
  ('RVR-AM-00685', 'Tractor Truck', 'Tata Motors Limited', 'Signa 4018', 'HS Diesel'),
  ('RVR-AM-00686', 'Tractor Truck', 'Ashok Leyland', '4019 LX', 'HS Diesel'),
  ('RVR-AM-00687', 'Tractor Truck', 'Eicher Motors Limited', 'Pro 5031 M', 'HS Diesel'),
  ('RVR-AM-00688', 'Tractor Truck - HR & KM Based', 'Tata Motors Limited', 'Signa 3518', 'HS Diesel'),
  ('RVR-AM-00689', 'Tractor Truck - HR & KM Based', 'AMW Motors Limited', '2516 HL', 'HS Diesel'),
  ('RVR-AM-00690', 'Tractor Truck - HR & KM Based', 'Ashok Leyland', '4018', 'HS Diesel'),
  ('RVR-AM-00691', 'Tractor Truck - HR & KM Based', 'Tata Motors Limited', 'Signa 4923', 'HS Diesel'),
  ('RVR-AM-00692', 'Tractor Truck - HR & KM Based', 'Tata Motors Limited', 'LPS3516', 'HS Diesel'),
  ('RVR-AM-00693', 'Tractor Truck - HR & KM Based', 'Ashok Leyland', '3518 IL', 'HS Diesel'),
  ('RVR-AM-00694', 'Tractor Truck - HR & KM Based', 'Eicher Motors Limited', 'PRO-6040', 'HS Diesel'),
  ('RVR-AM-00695', 'Tractor Truck - HR & KM Based', 'Bharat Benz', '2523R', 'HS Diesel'),
  ('RVR-AM-00696', 'Tractor Truck - HR & KM Based', 'Tata Motors Limited', 'Prima LX 4023.S', 'HS Diesel'),
  ('RVR-AM-00697', 'Tractor Truck - HR & KM Based', 'Ashok Leyland', '4620', 'HS Diesel'),
  ('RVR-AM-00698', 'Tractor Truck - HR & KM Based', 'Bharat Benz', '5532T', 'HS Diesel'),
  ('RVR-AM-00699', 'Tractor Truck - HR & KM Based', 'Tata Motors Limited', 'LPS 3518 TC', 'HS Diesel'),
  ('RVR-AM-00700', 'Transformer Outdoor Type Oil Cooled', 'Hyd. Instrument Transformers', '1000 kVA', NULL),
  ('RVR-AM-00701', 'Transformer Outdoor Type Oil Cooled', 'Hyd. Instrument Transformers', '500 kVA', NULL),
  ('RVR-AM-00702', 'Transformer Outdoor Type Oil Cooled', 'Hyd. Instrument Transformers', '1250 kVA', NULL),
  ('RVR-AM-00703', 'Transformer Outdoor Type Oil Cooled', 'VVE Transformers', '315 kVA', NULL),
  ('RVR-AM-00704', 'Transformer Outdoor Type Oil Cooled', 'VVE Transformers', '500 kVA', NULL),
  ('RVR-AM-00705', 'Transformer Outdoor Type Oil Cooled', 'VVE Transformers', '100 kVA', NULL),
  ('RVR-AM-00706', 'Transformer Outdoor Type Oil Cooled', 'VVE Transformers', '160 kVA', NULL),
  ('RVR-AM-00707', 'Transformer Outdoor Type Oil Cooled', 'VVE Transformers', '200 kVA', NULL),
  ('RVR-AM-00708', 'Transformer Outdoor Type Oil Cooled', 'VVE Transformers', '250 kVA', NULL),
  ('RVR-AM-00709', 'Transformer Outdoor Type Oil Cooled', 'CURRENT ELECTRICALS', '500 kVA', NULL),
  ('RVR-AM-00710', 'Transformer Outdoor Type Oil Cooled', 'Incred Industries', '500 kVA', NULL),
  ('RVR-AM-00711', 'Transformer Outdoor Type Oil Cooled', 'Incred Industries', '630 kVA', NULL),
  ('RVR-AM-00712', 'Transformer Outdoor Type Oil Cooled', 'Incred Industries', '250 kVA', NULL),
  ('RVR-AM-00713', 'Transformer Outdoor Type Oil Cooled', 'Kirloskar Electric', '500 kVA', NULL),
  ('RVR-AM-00714', 'Transformer Outdoor Type Oil Cooled', 'Powertech Transformers & Controls', '200 kVA', NULL),
  ('RVR-AM-00715', 'Transformer Outdoor Type Oil Cooled', 'Powertech Transformers & Controls', '400 kVA', NULL),
  ('RVR-AM-00716', 'Transformer Outdoor Type Oil Cooled', 'Powertech Transformers & Controls', '315 kVA', NULL),
  ('RVR-AM-00717', 'Transformer Outdoor Type Oil Cooled', 'Radhika Transformers', '160 kVA', NULL),
  ('RVR-AM-00718', 'Transformer Outdoor Type Oil Cooled', 'Servomax India', '160 kVA', NULL),
  ('RVR-AM-00719', 'Transformer Outdoor Type Oil Cooled', 'Servomax India', '315 kVA', NULL),
  ('RVR-AM-00720', 'Transformer Outdoor Type Oil Cooled', 'Servomax India', '500 kVA', NULL),
  ('RVR-AM-00721', 'Transformer Outdoor Type Oil Cooled', 'Sri Bhargav Electricals', '315 kVA', NULL),
  ('RVR-AM-00722', 'Transformer Outdoor Type Oil Cooled', 'Sri Bhargav Electricals', '250 kVA', NULL),
  ('RVR-AM-00723', 'Transformer Outdoor Type Oil Cooled', 'Sri Sri Ram Power Plant', '315 kVA', NULL),
  ('RVR-AM-00724', 'Transformer Outdoor Type Oil Cooled', 'Toshiba T&D Systems', '500 kVA', NULL),
  ('RVR-AM-00725', 'Tree Shear Attachment', 'OMEF-GROUP', 'BI400', NULL),
  ('RVR-AM-00726', 'Truck', 'Eicher Motors Limited', 'Pro 5016', 'HS Diesel'),
  ('RVR-AM-00727', 'Truck', 'Ashok Leyland', 'Ecomet 1214', 'HS Diesel'),
  ('RVR-AM-00728', 'Truck', 'Tata Motors Limited', 'LPT 1109', 'HS Diesel'),
  ('RVR-AM-00729', 'Truck', 'Bharat Benz', '914R', 'HS Diesel'),
  ('RVR-AM-00730', 'Truck', 'Tata Motors Limited', 'LPT 407', 'HS Diesel'),
  ('RVR-AM-00731', 'Truck', 'Tata Motors Limited', 'LPT 1613/42', 'HS Diesel'),
  ('RVR-AM-00732', 'Truck', 'Eicher Motors Limited', '1059', 'HS Diesel'),
  ('RVR-AM-00733', 'Truck', 'Ashok Leyland', '1415 HE', 'HS Diesel'),
  ('RVR-AM-00734', 'Truck', 'Eicher Motors Limited', 'Pro 1110', 'HS Diesel'),
  ('RVR-AM-00735', 'Truck', 'Tata Motors Limited', 'Ultra 1518', 'HS Diesel'),
  ('RVR-AM-00736', 'Truck', 'Ashok Leyland', 'Ecomet 1615', 'HS Diesel'),
  ('RVR-AM-00737', 'Truck', 'Tata Motors Limited', 'LPT 1512', 'HS Diesel'),
  ('RVR-AM-00738', 'Truck', 'Eicher Motors Limited', 'Pro 6028 L', 'HS Diesel'),
  ('RVR-AM-00739', 'Truck', 'Tata Motors Limited', 'T.16 Ultra', 'HS Diesel'),
  ('RVR-AM-00740', 'Truck', 'Tata Motors Limited', 'LPT 1412', 'HS Diesel'),
  ('RVR-AM-00741', 'Truck - HR & KM Based', 'Eicher Motors Limited', 'Pro 1075', 'HS Diesel'),
  ('RVR-AM-00742', 'Truck - HR & KM Based', 'Eicher Motors Limited', 'Pro 2110', 'HS Diesel'),
  ('RVR-AM-00743', 'Truck Crane - Hour Based', 'Action Construction Equipment', 'NX 360', 'HS Diesel'),
  ('RVR-AM-00744', 'Truck Crane - HR & KM Based', 'Sany Heavy Industry', 'STC 500', 'HS Diesel'),
  ('RVR-AM-00745', 'Truck Crane - HR & KM Based', 'Sany Heavy Industry', 'STC 800', 'HS Diesel'),
  ('RVR-AM-00746', 'Truck Crane - HR & KM Based', 'Zoomlion India', 'QY 70', 'HS Diesel'),
  ('RVR-AM-00747', 'Truck Crane - HR & KM Based', 'Zoomlion India', 'QY 60H', 'HS Diesel'),
  ('RVR-AM-00748', 'Truck Crane - HR & KM Based', 'Action Construction Equipment', 'TM 300', 'HS Diesel'),
  ('RVR-AM-00749', 'Truck Crane - HR & KM Based', 'Zoomlion India', 'ZLJ5419JQZ50V', 'HS Diesel'),
  ('RVR-AM-00750', 'Truck Crane - HR. KM and OpC Based', 'Liebherr CMCtec India Private Limited', 'LTM 1200', 'HS Diesel'),
  ('RVR-AM-00751', 'Truck Mounted Access Platform', 'Macons Socage Platform', 'DA324', 'HS Diesel'),
  ('RVR-AM-00752', 'Truck Mounted Access Platform', 'Macons Socage Platforms', 'DA224', 'HS Diesel'),
  ('RVR-AM-00753', 'Truck Mounted Access Platform', 'Ashok Leyland', 'Ecomet 1012', 'HS Diesel'),
  ('RVR-AM-00754', 'Truck Mounted Belt Conveyor', 'Schwing Stetter India', 'LB 40', 'HS Diesel'),
  ('RVR-AM-00755', 'Truck mounted Bitmen Sprayer', 'Apollo Equipments', 'ATM 6000', 'HS Diesel'),
  ('RVR-AM-00756', 'Truck mounted Bitmen Sprayer', 'Ashok Leyland', '1613 L', 'HS Diesel'),
  ('RVR-AM-00757', 'Truck Mounted Bowser', 'Tata Motors Limited', 'LPT 709 EX2', 'HS Diesel'),
  ('RVR-AM-00758', 'Truck Mounted Bowser', 'Mahindra and Mahindra Limited', 'Jayo DI 3200', 'HS Diesel'),
  ('RVR-AM-00759', 'Truck Mounted Bowser', 'Ashok Leyland', 'Boss 1112 LE', 'HS Diesel'),
  ('RVR-AM-00760', 'Truck Mounted Bowser', 'Eicher Motors Limited', 'Pro 2049', 'HS Diesel'),
  ('RVR-AM-00761', 'Truck Mounted Bowser', 'Tata Motors Limited', '407 GOLD+', 'HS Diesel'),
  ('RVR-AM-00762', 'Truck Mounted Bowser - ''HR & KM''', 'Tata Motors Limited', 'LPT 1612', 'HS Diesel'),
  ('RVR-AM-00763', 'Truck Mounted Bowser - ''HR & KM''', 'Tata Motors Limited', 'LTP 1616', 'HS Diesel'),
  ('RVR-AM-00764', 'Truck Mounted Bowser or Tanker', 'Tata Motors Limited', '407', 'HS Diesel'),
  ('RVR-AM-00765', 'Truck Mounted Bowser or Tanker', 'Tata Motors Limited', 'LPT 909', 'HS Diesel'),
  ('RVR-AM-00766', 'Truck Mounted Bowser or Tanker', 'Tata Motors Limited', 'LPT 2515', 'HS Diesel'),
  ('RVR-AM-00767', 'Truck Mounted Bowser or Tanker', 'Ashok Leyland', '2214', 'HS Diesel'),
  ('RVR-AM-00768', 'Truck Mounted Bowser or Tanker', 'Tata Motors Limited', 'LPT 2518', 'HS Diesel'),
  ('RVR-AM-00769', 'Truck Mounted Bowser or Tanker', 'Tata Motors Limited', 'LPT 2516', 'HS Diesel'),
  ('RVR-AM-00770', 'Truck Mounted Bowser or Tanker', 'Ashok Leyland', '1612 L', 'HS Diesel'),
  ('RVR-AM-00771', 'Truck Mounted Bowser or Tanker', 'Swaraj Mazda', 'Sartaj', 'HS Diesel'),
  ('RVR-AM-00772', 'Truck Mounted Bowser or Tanker', 'Eicher Motors Limited', 'Pro 2095 Xp', 'HS Diesel'),
  ('RVR-AM-00773', 'Truck Mounted Bowser or Tanker', 'Eicher Motors Limited', '20.16', 'HS Diesel'),
  ('RVR-AM-00774', 'Truck Mounted Bowser or Tanker', 'Tata Motors Limited', 'LPT 1613 BSIII', 'HS Diesel'),
  ('RVR-AM-00775', 'Truck Mounted Bowser or Tanker', 'Ashok Leyland', '1618 BS IV', 'HS Diesel'),
  ('RVR-AM-00776', 'Truck Mounted Bowser or Tanker', 'Tata Motors Limited', '912 LPT', 'HS Diesel'),
  ('RVR-AM-00777', 'Truck Mounted Concrete Pump -Boom Placer', 'Aquarius Engineers', '36.07', 'HS Diesel'),
  ('RVR-AM-00778', 'Truck Mounted Concrete Pump -Boom Placer', 'Putzmeister Concrete Machines', 'BSF 36.08 H', 'HS Diesel'),
  ('RVR-AM-00779', 'Truck Mounted MudTanker', 'Apollo Equipments', 'TM2CuM', 'HS Diesel'),
  ('RVR-AM-00780', 'Truck Mounted Self Loader Crane', 'Action Construction Equipment', 'SB123', 'HS Diesel'),
  ('RVR-AM-00781', 'Truck Mounted Self Loader Crane', 'Action Construction Equipment', 'SB163', 'HS Diesel'),
  ('RVR-AM-00782', 'Truck Mounted Tanker', 'Eicher Motors Limited', '30.25 xp', 'HS Diesel'),
  ('RVR-AM-00783', 'Truck Mounted Tanker', 'Ashok Leyland', '1616 BSIII', 'HS Diesel'),
  ('RVR-AM-00784', 'Truck Mounted Tanker', 'Tata Motors Limited', 'T.16 ULTRA DCR39', 'HS Diesel'),
  ('RVR-AM-00785', 'Truck Mounted Tanker', 'Ashok Leyland', 'EA1916/43 H COWL 295/90RT20', 'HS Diesel'),
  ('RVR-AM-00786', 'TugBoat', 'Mahindra and Mahindra Limited', '160 kVA Genset', 'HS Diesel'),
  ('RVR-AM-00787', 'Twin Boom Platform Lifter', 'Normet Oy', 'Himec 9905 BT', 'HS Diesel'),
  ('RVR-AM-00788', 'Utility Pickup Vehicle', 'Mahindra and Mahindra Limited', 'Bolero', 'HS Diesel'),
  ('RVR-AM-00789', 'Utility Pickup Vehicle', 'Mahindra and Mahindra Limited', 'Pickup', 'HS Diesel'),
  ('RVR-AM-00790', 'Utility Pickup Vehicle', 'Mahindra and Mahindra Limited', 'Genio', 'HS Diesel'),
  ('RVR-AM-00791', 'Utility Pickup Vehicle', 'Tata Motors Limited', '207 Rx', 'HS Diesel'),
  ('RVR-AM-00792', 'Utility Pickup Vehicle', 'Tata Motors Limited', 'ACE BS4', 'HS Diesel'),
  ('RVR-AM-00793', 'Utility Pickup Vehicle', 'Mahindra and Mahindra Limited', 'Imperio', 'HS Diesel'),
  ('RVR-AM-00794', 'Utility Pickup Vehicle', 'Force Motors', 'Trax Cruiser', 'HS Diesel'),
  ('RVR-AM-00795', 'Utility Pickup Vehicle', 'Tata Motors Limited', 'Yodha', 'HS Diesel'),
  ('RVR-AM-00796', 'Utility Pickup Vehicle', 'Ashok Leyland', 'Dost', 'HS Diesel'),
  ('RVR-AM-00797', 'Utility Pickup Vehicle', 'ISUZU Motors India', 'D-Max', 'HS Diesel'),
  ('RVR-AM-00798', 'Utility Pickup Vehicle', 'Tata Motors Limited', 'Intra V10', 'HS Diesel'),
  ('RVR-AM-00799', 'Utility Pickup Vehicle', 'Mahindra and Mahindra Limited', 'Camper GOLD', 'HS Diesel'),
  ('RVR-AM-00800', 'Utility Pickup Vehicle', 'Bentley Motors Limited', 'Bentayga Extended Wheelbase', 'HS Diesel'),
  ('RVR-AM-00801', 'Utility Pickup Vehicle', 'Maruti Suzuki', 'Ertiga Smart Hybrid', 'Petrol'),
  ('RVR-AM-00802', 'Utility Pickup Vehicle', 'Mahindra and Mahindra Limited', 'Bolero Neo N8', 'HS Diesel'),
  ('RVR-AM-00803', 'Utility Pickup Vehicle', 'Mahindra and Mahindra Limited', 'Bolero B6 BS-VI', 'HS Diesel'),
  ('RVR-AM-00804', 'Vertical Beam Welding Machine', 'Primo Automation Systems', 'WEB WIDTH 350-2840 MM', NULL),
  ('RVR-AM-00805', 'Vertical Shaft Impactor Crusher - Stationary', 'Puzzolana Machinery Fabricators', 'PVSI 750', NULL),
  ('RVR-AM-00806', 'Vertical Shaft Impactor Crusher - Stationary', 'Metso India', 'B7150SE', NULL),
  ('RVR-AM-00807', 'Vertical Shaft Impactor Crusher - Stationary', 'Puzzolana Machinery Fabricators', 'VSI-840', NULL),
  ('RVR-AM-00808', 'Vertical Shaft Impactor Crusher - Wheel Mounted', 'Metso India', 'NW7150D', NULL),
  ('RVR-AM-00809', 'Vibratory Compactor', 'Wirtgen India', 'Hamm 311', 'HS Diesel'),
  ('RVR-AM-00810', 'Vibratory Compactor', 'Escorts Construction Equipment', 'EC 5250', 'HS Diesel'),
  ('RVR-AM-00811', 'Vibratory Compactor', 'Volvo India Private Limited', 'SD110', 'HS Diesel'),
  ('RVR-AM-00812', 'Vibratory Compactor', 'Case New Holland CE', '1107', 'HS Diesel'),
  ('RVR-AM-00813', 'Vibratory Compactor', 'Larsen & Toubro Limited', '1190 D', 'HS Diesel'),
  ('RVR-AM-00814', 'Vibratory Compactor', 'Atlas Copco India Limited', 'CA255', 'HS Diesel'),
  ('RVR-AM-00815', 'Vibratory Compactor', 'Ingersoll Rand India Limited', '100 HD', 'HS Diesel'),
  ('RVR-AM-00816', 'Vibratory Compactor', 'Action Construction Equipment', 'ASD 115', 'HS Diesel'),
  ('RVR-AM-00817', 'Vibratory Compactor', 'Volvo India Private Limited', 'SD110BA', 'HS Diesel'),
  ('RVR-AM-00818', 'Vibratory Compactor', 'Caterpillar India Private Limited', 'CS54B', 'HS Diesel'),
  ('RVR-AM-00819', 'Vibratory Compactor', 'JCB India Limited', 'VM 116', 'HS Diesel'),
  ('RVR-AM-00820', 'Vibratory Compactor', 'Wirtgen India', 'HD 99i', 'HS Diesel'),
  ('RVR-AM-00821', 'Vibratory Compactor', 'AMMANN', 'ARS 110.2 CEV St.IV', 'HS Diesel'),
  ('RVR-AM-00822', 'Vibratory Compactor', 'Wirtgen India', 'HC 119iD', 'HS Diesel'),
  ('RVR-AM-00823', 'Walk Behind Laser Screed', 'Topall Impex', 'LS325', 'HS Diesel'),
  ('RVR-AM-00824', 'Walk Behind Vibratory Roller', 'Atlas Copco India Limited', 'LP 6500', 'HS Diesel'),
  ('RVR-AM-00825', 'Walk Behind Vibratory Roller', 'Greaves Cotton Limited', 'GWR – 2500DD - FH', 'HS Diesel'),
  ('RVR-AM-00826', 'Walk Behind Vibratory Roller', 'Greaves Cotton Limited', '1520', 'HS Diesel'),
  ('RVR-AM-00827', 'Walk Behind Vibratory Roller', 'Husqvarna Construction', 'LP 6500 I', 'HS Diesel'),
  ('RVR-AM-00828', 'Walk Behind Vibratory Roller', 'Redline by Dynapac', 'RW750D', 'HS Diesel'),
  ('RVR-AM-00829', 'Walk Behind Vibratory Roller', 'Wacker Neuson', 'RD7 KEH C2B303', 'HS Diesel'),
  ('RVR-AM-00830', 'Water Pump - Engine Driven', 'Cosmos Pumps', 'CAP 150H/EW', 'HS Diesel'),
  ('RVR-AM-00831', 'Water Pump - Engine Driven', 'Hitec Pump Industries', 'HDD 150', 'HS Diesel'),
  ('RVR-AM-00832', 'Weight Bridge', 'Essae Digitronics', 'TM-969', NULL),
  ('RVR-AM-00833', 'Weight Bridge', 'Essae Digitronics', 'TM-987', NULL),
  ('RVR-AM-00834', 'Weight Bridge', 'Avery India', '100 MT', NULL),
  ('RVR-AM-00835', 'Weight Bridge', 'Avery India', '120 MT', NULL),
  ('RVR-AM-00836', 'Weight Bridge', 'Essae Digitronics', '150 Tons', NULL),
  ('RVR-AM-00837', 'Weight Bridge', 'Eagle Scale', '100 MT', NULL),
  ('RVR-AM-00838', 'Weight Bridge', 'Tulaman', '100 MT', NULL),
  ('RVR-AM-00839', 'Weight Bridge', 'Tulaman', '60 MT', NULL),
  ('RVR-AM-00840', 'Weight Bridge', 'Ashbee Systems', '80T', NULL),
  ('RVR-AM-00841', 'Weight Bridge', 'Essae Digitronics', 'TM-950', NULL),
  ('RVR-AM-00842', 'Weight Bridge', 'Ashbee Systems', '60T', NULL),
  ('RVR-AM-00843', 'Weight Bridge', 'Sri Modern Weigh System', 'MWS-WB', NULL),
  ('RVR-AM-00844', 'Weight Bridge', 'Sri Modern Weigh System', 'MW-WB', NULL),
  ('RVR-AM-00845', 'Weight Bridge', 'Endeavour Instrument', '80MT', NULL),
  ('RVR-AM-00846', 'Welding Machine', 'Prakash Group', '4.5 kVA', 'HS Diesel'),
  ('RVR-AM-00847', 'Welding Unit', 'Ador Welding Ltd', 'Champ T400', NULL),
  ('RVR-AM-00848', 'Welding Unit', 'Ador Welding Ltd', 'SILENT CHALLENGER 501 ( SC 501)', NULL),
  ('RVR-AM-00849', 'Wet Mix Macadam Plant', 'Ashish Construction Equipment', 'WM 100', NULL),
  ('RVR-AM-00850', 'Wet Mix Macadam Plant', 'Apollo Equipments', 'WMP 200', NULL),
  ('RVR-AM-00851', 'Wet Mix Macadam Plant', 'Vibrant Construction Equipment', 'WMM 250', NULL),
  ('RVR-AM-00852', 'Wheel Loader', 'Caterpillar India Private Limited', 'HM 2021D', 'HS Diesel'),
  ('RVR-AM-00853', 'Wheel Loader', 'Liugong India', 'CLG 856', 'HS Diesel'),
  ('RVR-AM-00854', 'Wheel Loader', 'Liugong India', 'CLG 835', 'HS Diesel'),
  ('RVR-AM-00855', 'Wheel Loader', 'JCB India Limited', '430 ZX', 'HS Diesel'),
  ('RVR-AM-00856', 'Wheel Loader', 'Liugong India', 'CLG 836', 'HS Diesel'),
  ('RVR-AM-00857', 'Wheel Loader', 'Caterpillar India Private Limited', '950 GC', 'HS Diesel'),
  ('RVR-AM-00858', 'Wheel Loader', 'JCB India Limited', '455ZX', 'HS Diesel'),
  ('RVR-AM-00859', 'Wheel Loader', 'Bull Machines', 'Smart 60', 'HS Diesel'),
  ('RVR-AM-00860', 'Wheel Loader', 'Larsen & Toubro Limited', '9020', 'HS Diesel'),
  ('RVR-AM-00861', 'Wheel Loader', 'Caterpillar India Private Limited', 'HM 2021E', 'HS Diesel'),
  ('RVR-AM-00862', 'Wheel Loader', 'Liugong India', '870H', 'HS Diesel'),
  ('RVR-AM-00863', 'Wheel Loader', 'JCB India Limited', '433-4', 'HS Diesel'),
  ('RVR-AM-00864', 'Wheel Loader', 'Liugong India', 'CLG 838H', 'HS Diesel'),
  ('RVR-AM-00865', 'Wheel Loader', 'JCB India Limited', '433-5', 'HS Diesel'),
  ('RVR-AM-00866', 'Wheel Loader', 'Liugong India', 'CLG 850T', 'HS Diesel'),
  ('RVR-AM-00867', 'Wheel Loader', 'Liugong India', 'CLG 838T', 'HS Diesel')
ON CONFLICT (am_id) DO NOTHING;
