const router = require('express').Router();

router.use('/auth',            require('./auth'));
router.use('/projects',        require('./projects'));
router.use('/machines',        require('./machines'));
router.use('/entries',         require('./entries'));
router.use('/fuel',            require('./fuel'));
router.use('/service',         require('./service'));
router.use('/operators',       require('./operators'));
router.use('/attendance',      require('./attendance'));
router.use('/spare-parts',     require('./spareParts'));
router.use('/breakdown',       require('./breakdown'));
router.use('/payroll',         require('./payroll'));
router.use('/reports',         require('./reports'));
router.use('/equipment-types',   require('./equipmentTypes'));
router.use('/fuel-type-options', require('./fuelTypeOptions'));
router.use('/users',           require('./users'));
router.use('/uom',             require('./uom'));
router.use('/vendors',         require('./vendors'));
router.use('/designations',    require('./designations'));
router.use('/hire',            require('./hireWorkOrders'));
router.use('/hire-indents',    require('./hireIndents'));
router.use('/hire-billing',    require('./hireBilling'));
router.use('/gst',             require('./gst'));
router.use('/kala',            require('./kala'));
router.use('/compliance',           require('./compliance'));
router.use('/machine-documents',    require('./machineDocuments'));
router.use('/reading-types',        require('./readingTypes'));
router.use('/reading-mappings',     require('./readingMappings'));
router.use('/machine-reading-configs', require('./machineReadingConfigs'));
router.use('/asset-matrix',            require('./assetMatrix'));
router.use('/fuel-records',            require('./fuelRecords'));
router.use('/meter-resets',            require('./meterResets'));
router.use('/meter-reset-requests',    require('./meterResetRequests'));
router.use('/notifications',           require('./notifications'));
router.use('/permissions',             require('./permissions'));
router.use('/fuel-stations',           require('./fuelStations'));
router.use('/asset-group-configs',     require('./assetGroupConfigs'));
router.use('/equipment-type-configs',  require('./equipmentTypeConfigs'));

module.exports = router;
